### ISSUE TITLE
repl var undef

### ISSUE THREAD

**Issue by jbcaillau** [control-toolbox/CTBase.jl#102]
@ocots small bug, seemingly variable visibility
```julia
julia> t0 = 0
0

julia> tf = 1
1

ct> t ∈ [t0, tf], time

debug> parsing string: t ∈ [t0, tf], time
debug> expression parsed: (t ∈ [t0, tf], time)
debug> expression type: Expr
Expr
  head: Symbol tuple
  args: Array{Any}((2,))
    1: Expr
      head: Symbol call
      args: Array{Any}((3,))
        1: Symbol ∈
        2: Symbol t
        3: Expr
          head: Symbol vect
          args: Array{Any}((2,))
            1: Symbol t0
            2: Symbol tf
    2: Symbol time
debug> dump of expression: nothing
debug> command: non_existing_command
debug> try to add expression: (t ∈ [t0, tf], time)
debug> code: begin
    (t ∈ [t0, tf], time)
end
debug> quote code: begin
    #= /home/caillau/.julia/packages/CTBase/7IBsO/src/repl.jl:307 =#
    #= /home/caillau/.julia/packages/CTBase/7IBsO/src/repl.jl:307 =# @def var"##294" begin
            (t ∈ [t0, tf], time)
        end
end
Line 1: (t ∈ [t0, tf], time)
debug> exception thrown: UndefVarError(:t0)

Invalid expression.
```

**Comment by jbcaillau** [comment]
@ocots other small problem: error when relaunching the REPL
```julia
julia> ctrepl(debug=false)
To start, you should set the name of the optimal control problem and the name of the solution.
For example, you can type:

    ct> NAME=(ocp, sol)

┌ Warning: REPL key '>' overwritten.
└ @ ReplMaker ~/.julia/packages/ReplMaker/ViCwA/src/ReplMaker.jl:96
ERROR: deepcopy of Modules not supported
```

**Comment by jbcaillau** [comment]
@ocots `NAME` used alone could (should) return the current values of the problem and solution names.

**Comment by ocots** [comment]
The second bu is corrected and when `NAME` print the current values.

For the first bug, it comes from the fact that I make a test on the validity of the current ocp definition:

https://github.com/control-toolbox/CTBase.jl/blob/2d0a90687bf4f5d325f33269454593784c4aec5c/src/repl.jl#L97

This `eval` does not contain the main repl context. Maybe I should quote the `eval` test with a mechanism to tell to do the following if no error has been thrown. Another possibility is to give all the context to the `eval` part inside the macro but I don't know how to do that.

**Comment by jbcaillau** [comment]
@ocots yes, context issue. don't know right now how to solve it but should be standard. (The `quote` way you point is more or less what I did for `@def`.)

**Comment by ocots** [comment]
This is solved.

**Comment by jbcaillau** [comment]
properly, me hope 🤭
