### ISSUE TITLE
Julia Help ! 

### ISSUE THREAD

**Issue by j-l-s** [control-toolbox/CTBase.jl#11]
I spent some time struggling with a `map.()` (map on array) call on the args part of an expression....

I posted this on julialang.org:  https://discourse.julialang.org/t/problem-using-map-with-expr-args/96257 
As Julia's experts, you may (must !!!) have an idea how to call map.() properly on an expr.args

**Comment by ocots** [comment]
Does this may be useful?

http://fluxml.ai/MacroTools.jl/stable/pattern-matching/#Expression-Walking-1

**Comment by jbcaillau** [comment]
@j-l-s Check [this](https://github.com/control-toolbox/CTBase.jl/issues/9#issuecomment-1474463198)

**Comment by jbcaillau** [comment]
> Does this may be useful?
> 
> http://fluxml.ai/MacroTools.jl/stable/pattern-matching/#Expression-Walking-1

Does this may really be English, Mr Cots 😱?

**Comment by ocots** [comment]
My english depends on the time.
