### ISSUE TITLE
Documentation of Types and Functions

### ISSUE THREAD

**Issue by ocots** [control-toolbox/CTBase.jl#110]
@BaptisteCbl I would prefer to merge the doc from `types.jl` and `functions.jl` into `types.jl`. It will be simpler for the user to find info.

Could you do the merge?

**Comment by BaptisteCbl** [comment]
Hi, 
Ok, should I just move the docs that refer to the constructors like [here](https://github.com/control-toolbox/CTBase.jl/blob/9d50bb5cd2ae967ee2d0b610b193105c31b4364a/src/functions.jl#L176) or also the docs of the calls that compute the value of the object at a given point like [here](https://github.com/control-toolbox/CTBase.jl/blob/9d50bb5cd2ae967ee2d0b610b193105c31b4364a/src/functions.jl#L216)  ?

**Comment by ocots** [comment]
Constructors and calls. Everything in the same docstring. Each docstring must explain how to construct and call.
