### ISSUE TITLE
Functional constraints: revise

### ISSUE THREAD

**Issue by jbcaillau** [control-toolbox/CTBase.jl#113]
Revise the functional declaration of constraints building all variants on an update on the version with named arguments below:

![image](https://github.com/control-toolbox/CTBase.jl/assets/62183989/07ca212f-4712-4c65-a412-ae4c3cbd11ff)

Todo:
- covers all types `:initial, :final, :boundary, :control, :state, :mixed, :variable`
- no more `val` keyword, no more `Index` type; just `rg`, possibly with a single integer value instead of a mere range 
- a constraint is either linear (range) or not (function)
- equalities are encoded by equal lower and upper bounds
- no bound means +/- (vector of) `Inf`

@BaptisteCbl any comment?

**Comment by BaptisteCbl** [comment]
Hi. It does seem easier that way. 
I'll do it and make a PR once it's done. 
If I'm not mistaken the presentation is today, good luck with it!

**Comment by BaptisteCbl** [comment]
> Revise the functional declaration of constraints building all variants on an update on the version with named arguments below:
> 
> ![image](https://user-images.githubusercontent.com/62183989/256696927-07ca212f-4712-4c65-a412-ae4c3cbd11ff.jpeg)
> 
> Todo:
> 
>     * covers all types `:initial, :final, :boundary, :control, :state, :mixed, :variable`
> 
>     * no more `val` keyword, no more `Index` type; just `rg`, possibly with a single integer value instead of a mere range
> 
>     * a constraint is either linear (range) or not (function)
> 
>     * equalities are encoded by equal lower and upper bounds
> 
>     * no bound means +/- (vector of) `Inf`
> 
> 
> @BaptisteCbl any comment?

Just about the Inf when there are no bounds, I think we must reject case with both lb, ub not provided because we can't know the dimension especially with a constraint as a function (and to be coherent maybe reject with rg too).

**Comment by jbcaillau** [comment]
greetings @BaptisteCbl from Boston airport! yes, there are forbidden combinations:
- neither `lb` nor `ub` provided [^1]
- `rg` and `f` provided (a constraint is either linear *xor* nonlinear)

[^1]: if only one is provided, the other is a vector of `+/-Inf`

**Comment by jbcaillau** [comment]
and yes, it would be nice to clean / delete some useless constraint functions

**Comment by BaptisteCbl** [comment]
Hello,
Ok, thanks for the precisions !

**Comment by jbcaillau** [comment]
@BaptisteCbl Closing this issue on the basis of [this PR](https://github.com/control-toolbox/CTBase.jl/pull/116)
