### ISSUE TITLE
Performance: add pre-allocation in nlp_constraints

### ISSUE THREAD

**Issue by jbcaillau** [control-toolbox/CTBase.jl#114]
@ocots we must revise `nlp_constraints` replacing `append!` by pre-allocations:

https://github.com/control-toolbox/CTBase.jl/blob/3e246d90e83b630e50b1115d26ca8b1bbacfeca6/src/model.jl#L1068

For the record, we know the sizes of constraints by looking at the lower / upper bounds (at least one is provided).

**Comment by ocots** [comment]
Someone wants to do that?

**Comment by jbcaillau** [comment]
https://youtu.be/SUYI7kIR0S4?si=5P9vIdV1v00p8zxg

**Comment by jbcaillau** [comment]
Taking care of this in https://github.com/control-toolbox/CTBase.jl/issues/166
