### ISSUE TITLE
Functional: revise time!

### ISSUE THREAD

**Issue by jbcaillau** [control-toolbox/CTBase.jl#115]
@BaptisteCbl @ocots Keep the `Index` type only for internal (not user) purposes. For `constraints!`, it should be OK with [this issue](https://github.com/control-toolbox/CTBase.jl/issues/113), and for `time!` one could also use something like
```julia
time!(;t0, ind0, tf, indf)
```

**Comment by jbcaillau** [comment]
@BaptisteCbl Hope you are doing well. Late question on this:
- can you please confirm that you haven't touched this point (update of `time!`)
- do we agree that, from the user viewpoint, in the current version of the code the `time!` function is the only place where the `Index` type is still used?

**Comment by BaptisteCbl** [comment]
Hello, I hope you are doing well too. 
I have indeed not touched the ```time!``` function, and yes, for the user Index is only useful for ```time!```.

**Comment by ocots** [comment]
@jbcaillau Can we close this issue?

**Comment by jbcaillau** [comment]
@ocots not yet; we should actually suppress this `Index` thing in the API, replacing it by a version of `time!` using named args (just like @BaptisteCbl did for the constraints). Check [above](https://github.com/control-toolbox/CTBase.jl/issues/115#issue-1827430821).
