### ISSUE TITLE
Code in the `parser` branch of `OptimalControl.jl` should be moved to the `CTBase.jl` repo.

### ISSUE THREAD

**Issue by ocots** [control-toolbox/CTBase.jl#12]
@j-l-s @ocots Code in the `parser` branch of `OptimalControl.jl` should be moved to the [`CTBase.jl`](https://github.com/control-toolbox/CTBase.jl) repo.

_Originally posted by @jbcaillau in https://github.com/control-toolbox/CTBase.jl/issues/9#issuecomment-1474827854_

**Comment by jbcaillau** [comment]
Mr @ocots you don't like links within titles 🙂?

**Comment by ocots** [comment]
It seems it is not interpreted.

**Comment by ocots** [comment]
@jbcaillau @j-l-s I have moved `CtParser` into `CTBase.jl`. See https://github.com/control-toolbox/CTBase.jl/tree/parser

**Comment by ocots** [comment]
See
* src/ctparser.jl
* src/ctparser-utils.jl
* test/runtests.jl
* test/test_ctparser.jl
* test/test_ctparser_utils.jl

Remark: the test of ctparser is commented and it is not working.
