### ISSUE TITLE
Functional constraints

### ISSUE THREAD

**Issue by jbcaillau** [control-toolbox/CTBase.jl#123]
@BaptisteCbl Following comments in [previous PR](https://github.com/control-toolbox/CTBase.jl/pull/116#issuecomment-1748898149):
- on the main version of `constraint!` (= the one with named args that factors out the code and is called by other / older versions without named args), we use `lb/ub=Nothing` if no bound (instead of `+/-[ Inf, ... ]`)
- all other versions of `constraint!` (= without named args) do not have any default values and call the previous one (no code duplication)

When it is OK, can you please make a PR from your fork towards the `constraint_revise` branch?

PS. I suspect that the new version will also solve [#122]

**Comment by ocots** [comment]
If the other constraints! functions have no default values I suggest to change them as internal by writing __constraints!. Otherwise it may be confusing for the user.

I am not sure I haven't looked closely  the code.

**Comment by jbcaillau** [comment]
@ocots For now, I advocate keeping them to ensure compatibility with previous functional syntax.

> If the other constraints! functions have no default values I suggest to change them as internal by writing __constraints!. Otherwise it may be confusing for the user.
> 
> I am not sure I haven't looked closely the code.

**Comment by jbcaillau** [comment]
@BaptisteCbl Hi! Just merged this (long pending) PR: thanks for the job. Will have soon a closer look at the resulting changes in the related [branch](https://github.com/control-toolbox/CTBase.jl/tree/constraint_revise).

**Comment by ocots** [comment]
@jbcaillau have a look at https://github.com/control-toolbox/CTBase.jl/pull/147
