### ISSUE TITLE
Abstract Bolza

### ISSUE THREAD

**Issue by ocots** [control-toolbox/CTBase.jl#124]
This does not work:

```julia
y₂(tf)^2 + z₂(tf)^2 + ∫( 1e-6 * v(t) ) → max
```

but this is ok:

```julia
( y₂(tf)^2 + z₂(tf)^2 ) + ∫( 1e-6 * v(t) ) → max
```

**Comment by jbcaillau** [comment]
yes. sum of two expressions, not three. needs to be documented, see [this issue](https://github.com/control-toolbox/OptimalControl.jl/issues/155)

**Comment by ocots** [comment]
Again, it took me time to understand that this was the problem!
