### ISSUE TITLE
Plots

### ISSUE THREAD

**Issue by jbcaillau** [control-toolbox/CTBase.jl#128]
@ocots add a recipe instead of using / importing Plots.jl (the user will have to do `using Plots` to plot an ocp solution)

**Comment by ocots** [comment]
I think we can close this one since I already use recipes when needed. Besides, I think that we have changed our minds and we prefer that the user only do `using OptimalControl` and can plot a solution. Actually I am not sure. We should make a decision.

**Comment by jbcaillau** [comment]
To be solved by https://github.com/control-toolbox/OptimalControl.jl/issues/179
