### ISSUE TITLE
Scalar control / state

### ISSUE THREAD

**Issue by jbcaillau** [control-toolbox/CTBase.jl#13]
@ocots When the control is scalar (or the state - the latter is rather rare, though) the user probably wants to refer to it according to `x` rather than `x[1]`. So the type of the state should not be `Vector{Real}` but `Real`, in this case. And the user code should be written according to this convention.

Note that
```julia
x = 2
x[1]
x * [ 1, 2, 3 ]
```
are OK, while
```julia
x[1:1]
[ 1 ] * [ 1, 2, 3 ]
```
are not.

So my feeling is that we should be able to avoid the `:scalar_vectorial` thing, maybe up to some
```julia
const State = Union{Real, Vector{<:Real}} 
```
and assuming that the user has a sound usage of this convention. In particular, something like
```julia
control!(ocp, 1)
constraint!(ocp, :control, [ 0 ], [ 1 ])
```
is not allowed and should be written
```julia
constraint!(ocp, :control, 0, 1) # 0 ≤ u(t) ≤ 1
```
This does not preclude the use of the control according to `u[1]`.

**Comment by jbcaillau** [comment]
@ocots Are you OK that we can impose that one-dimensional control / state must be scalar (not vectorial)? And that is more or less solves any issue with this, provided the internal code takes this into account (*à la* `append!`)?

**Comment by ocots** [comment]
But in `CTDirect.jl` for instance, when we call the dynamics, we would have to test if $x$ and/or $u$ is scalar to be sure to give a scalar instead of a vector. See [here](https://github.com/control-toolbox/CTDirect.jl/blob/main/src/problem.jl#L52) for instance. The idea of the usage is to handle this internally. Since the usage is scalar by default, we can impose that one-dimensional control / state must be scalar (not vectorial) and it does everything as we expect.

For me, we can remove this usage if we do not have to test anything but I am not sure that it is possible. Ok for the `append!`, but for a call?

**Comment by PierreMartinon** [comment]
In CTDirect, if I remember correctly we always uses getters such as get_state() or get_control(), so any specific handling *may* be done in these functions. What is less clear to me is the practical impact on the definition of the ocp functions: do we have multiple definitions with scalar / vector arguments (with maybe one calling the other) ?

**Comment by jbcaillau** [comment]
@PierreMartinon Not sure about where you want to go: to be discussed this Friday

@ocots I confirm that it is a bit unnatural (for the user) to retrieve (`ocp.dynamics`) a function with vector args when defining a dynamics with scalar ones. Another reason to let the user do as they want (provided they comply with `Julia` syntax for scalar / vector stuff).

**Comment by ocots** [comment]
I agree with the fact that we can use append! and push! to handle this.

I never intended to provide to the user something he didn't give. It was only internal. I am making some changes to take into account only the time dependence. 

But to be nice to Pierre and Joseph, there will be still an internal usage. Same callings but completely internal and more efficient than before.

For CTFlows for instance I won't use this mechanism. 

To be discussed.

**Comment by jbcaillau** [comment]
@ocots Do we agree that the `Mayer` wrapper below from `functions.jl` is not needed anymore?
```julia
# classical call
function (F::Mayer{N})(t0::Time, x0::Union{ctNumber, State}, 
    tf::Time, xf::Union{ctNumber, State}, args...; kwargs...)::ctNumber where {N}
    return F.f(t0, x0, tf, xf, args...; kwargs...)
end

# specific calls: inputs are vectors, except times
function (F::Mayer{1})(t0::_Time, x0::State, tf::_Time, xf::State, args...; kwargs...)::ctNumber
    return F.f(t0.value, x0[1], tf.value, xf[1], args...; kwargs...)
end
function (F::Mayer{N})(t0::_Time, x0::State, tf::_Time, xf::State, args...; kwargs...)::ctNumber where N
    return F.f(t0.value, x0, tf.value, xf, args...; kwargs...)
end
```

**Comment by ocots** [comment]
Not needed or must be updated to take into account variables?

**Comment by ocots** [comment]
Not needed or must be updated to take into account variables?

Because there are other functions which need to be updated.

**Comment by jbcaillau** [comment]
@ocots Must be. Take your time.

**Comment by ocots** [comment]
Do you prefer to have only 1 variable `v` or a varargin of variables of type Variable:

Either

```julia
Variable = Union{Real, Vector{<:Real}}
(x0::State, xf::State, v::Variable)::ctNumber
```

or 

```julia
Variable = Union{Real, Vector{<:Real}}
(x0::State, xf::State, vars::Variable...)::ctNumber
```

**Comment by ocots** [comment]
We could have

```julia
t0, tf ∈ R x R, variable
```

and in this case, we have two variables.

**Comment by jbcaillau** [comment]
Only one, as for `time`, `state` and `control`. Actually, all this is eased by aliases. On your example:
```julia
v ∈ R², variable
t0 = v₁
tf = v₂ 
t ∈ [ t0, tf ], time
```
(`onepass` tests already perform this kind of things)

And this is coherent with `variable!` routine in the functional setting (also implemented in the [`variables` branch](https://github.com/control-toolbox/CTBase.jl/blob/variables/src/model.jl)
```julia
function variable!(ocp::OptimalControlModel, q::Dimension, names::Union{String, Vector{String}}=__variable_names(q))
    (q > 1) && (names isa Vector{String}) && (length(names) ≠ q) && throw(InconsistentArgument("the number of variables names must be equal to the variable dimension"))
    (q == 1) && (names isa Vector{String}) && throw(InconsistentArgument("if the variable dimension is 1, then, the argument names must be a String"))
    (q > 1) && (names isa String) && (names = [ names * ctindices(i) for i ∈ range(1, q)])
    ocp.variable_dimension = q
    ocp.variable_names = (q == 1) ? [names] : names
end

function variable!(ocp::OptimalControlModel, q::Dimension, name::Symbol)
    variable!(ocp, q, string(name))
end
```

**Comment by ocots** [comment]
Ok.

Is this possible?

```julia
t0 ∈ R, variable
tf ∈ R, variable
```

**Comment by jbcaillau** [comment]
I prefer not to allow this. There is only one variable, as for time, state and control; then with aliases it is still possible to write nice code.

NB. Check this (automatic aliases for indices / exponents):
```julia
o = @def1 begin
    z ∈ R², variable
    s ∈ [ 0, z₁ ], time
    y ∈ R⁴, state
    w ∈ R, control
    r = y₃
    v = y₄
    aa = y₁ + w² + v³ + z₂
    y'(s) == [ aa(s), r²(s), 0, 0 ]
    r(0) + v(z₁) + z₂ → min
end
z = [ 5, 6 ]
y = [ 1, 2, 3, 4 ]
y0 = y
yf = 3y0
w = 7
@test o.dynamics(y, w, z) == [ y[1] + w^2 + y[4]^3 + z[2], y[3]^2, 0, 0 ]
@test o.mayer(y0, yf, z) == y0[3] + yf[4] + z[2]
```

**Comment by ocots** [comment]
Maybe we need to update the doc but this is done.
