### ISSUE TITLE
ocp printing

### ISSUE THREAD

**Issue by jbcaillau** [control-toolbox/CTBase.jl#134]
@ocots add the information whether the ocp is Autonomous / NonAutonomous, Fixed / NonFixed

**Comment by ocots** [comment]
I show different cases.

<img width="578" alt="Capture d’écran 2024-05-20 à 12 05 12" src="https://github.com/control-toolbox/CTBase.jl/assets/66357348/8c73b0ee-7285-4152-87d6-efc434123e38">
<img width="647" alt="Capture d’écran 2024-05-20 à 12 05 30" src="https://github.com/control-toolbox/CTBase.jl/assets/66357348/1850dc11-3d1b-4078-87d4-02a3ddd2e0a0">
<img width="577" alt="Capture d’écran 2024-05-20 à 12 05 40" src="https://github.com/control-toolbox/CTBase.jl/assets/66357348/5b7e2521-ff10-4375-8176-5639ca45ae2b">
<img width="574" alt="Capture d’écran 2024-05-20 à 12 05 50" src="https://github.com/control-toolbox/CTBase.jl/assets/66357348/3026efcf-e8cb-40e3-aa62-ea1ce9b88dc8">

**Comment by jbcaillau** [comment]
@ocots very nice, thanks. I suggest to change the superscript `!` to `*` that is the standard for compulsory stuff. Ready to merge?

**Comment by ocots** [comment]
It is just that I can't find the superscript asterisk. But I can change with `*`.

**Comment by ocots** [comment]
Ready to merge: https://github.com/control-toolbox/CTBase.jl/pull/135

**Comment by jbcaillau** [comment]
> It is just that I can't find the superscript asterisk. But I can change with `*`.

Oh! I would have bet it existed! Fine, then.
