### ISSUE TITLE
Variables

### ISSUE THREAD

**Issue by jbcaillau** [control-toolbox/CTBase.jl#14]
@ocots @PierreMartinon @joseph-gergaud It is useful to be able to declare (finite dimensional) *variables*, that is optimisation variables, for a control problem. For instance, when free the final time is a variable. In abstract form, this is
```julia
tf ∈ R, variable
t ∈ [ t0, tf ], time
```

Same for the initial time, when free (more rare). There can be also other variables. All of them must be arguments of the functions associated with the ocp, so as to be passed when evaluating the ocp. This implies a slight change of the API, at least for boundary constraints whose default signature must be
```julia
(x0, xf) -> f(x0, xf)
```
when the final time is fixed, and
```julia
(x0, xf, tf) -> f(x0, xf, tf)
```
when it is free (= variable). Same for Mayer (and Bolza) cost. 

*Remark.* A variable is different from a *parameter* (typically a homotopy parameter) on which no optimisation is performed. We'll also need to be able to add such *parameters*.

**Comment by PierreMartinon** [comment]
Maybe add two vectors for all ocp functions containing the (optional) fixed parameters and variables ?

**Comment by ocots** [comment]
Note that we can call any function with additional arguments. Here is the code of [DynamicsFunction](https://github.com/control-toolbox/CTBase.jl/blob/main/src/functions.jl#L126)
```julia
# -------------------------------------------------------------------------------------------
# pre-condition: f returns a scalar if scalar usage and x scalar as input
function_name=:DynamicsFunction
#
@eval @ctfunction_td_sv $(function_name), $(abstract_heritance)
# handling time dependence and scalar / vectorial usage
# output: vectorial
@eval function (F::$(function_name){time_dependence, scalar_vectorial})(t::Time, 
    x::State, u::Control, args...; kwargs...) where {time_dependence, scalar_vectorial}
    t_ = time_dependence==:autonomous ? () : (t, )
    x_ = (scalar_vectorial==:scalar && length(x)==1) ? (x[1], ) : (x, )
    u_ = (scalar_vectorial==:scalar && length(u)==1) ? (u[1], ) : (u, )
    y = F.f(t_..., x_..., u_..., args...; kwargs...)
    if scalar_vectorial==:scalar && length(x)==1
        if !(y isa MyNumber)
            throw(IncorrectOutput("A Dynamics function must return a Real (scalar)" *
            " if the input x and the usage are scalar."))
        end
        return [y]
    else
        return y
    end
end
```

**Comment by jbcaillau** [comment]
@ocots very clean. i am convinced for autonomous / non autonomous. we have to work on examples, for instance this code
```julia
t ∈ [ 0, tf ], time
z ∈ R², variable
...
x(tf)[1:2] - z == 0    (1)
```
should parse to
```julia
constraint!(ocp, :boundary, (xf, z) -> xf[1:2] - z, :eq1)
```
and `z` to calls to the functions we build. could be nice to use named args (=`kwargs`) for the variables.

**Comment by jbcaillau** [comment]
ps. on a related topic
https://discourse.julialang.org/t/extracting-kwargs-from-anonymous-function/37350/10

**Comment by jbcaillau** [comment]
@PierreMartinon Since we have closures, there is no need to add parameters. But we need variables that are additional optimisation unknowns.
> Maybe add two vectors for all ocp functions containing the (optional) fixed parameters and variables ?

**Comment by jbcaillau** [comment]
@ocots related to #59: is there any reason to cast the provided function (according to autonomous / not) or dynamics
```julia
XXX
```
but not for other constraints ? (*) 
```julia
function constraint!(ocp::OptimalControlModel, type::Symbol, f::Function, val, label::Symbol=__constraint_label())

    # check if the constraint named label already exists
    if label ∈ constraints_labels(ocp)
        throw(UnauthorizedCall("the constraint named " * String(label) * " already exists."))
    end

    # set the constraint
    if type ∈ [ :boundary, :control, :state, :mixed, :variable ]
        ocp.constraints[label] = (type, f, val, val)
    else
        throw(IncorrectArgument("the following type of constraint is not valid: " * String(type) *
        ". Please choose in [ :boundary, :control, :state, :mixed ] or check the arguments of the constraint! method."))
    end

end
```

(*) The cast on constraints is actually done in `nlp_constraints`, *e.g.*
```julia
        (:control, f::Function, lb, ub) => begin
            push!(ξf, ControlConstraint(f, time_dependence=time_dependence, control_dimension=m, constraint_dimension=length(lb)))
            append!(ξl, lb)
            append!(ξu, ub) end
```

**Comment by ocots** [comment]
I don't understand...

**Comment by ocots** [comment]
Variables have been added:

https://github.com/control-toolbox/CTBase.jl/blob/212f3d1869e049acf514ab0a82d755756d7388f0/src/model.jl#L117
