### ISSUE TITLE
`Variable / NonVariable` instead of `Fixed / NonFixed`

### ISSUE THREAD

**Issue by ocots** [control-toolbox/CTBase.jl#151]
@ocots at some point, we should switch to `Variable / NonVariable` instead of `Fixed / NonFixed` (maybe keeping the old syntax). I plead guilty on this 🙁

_Originally posted by @jbcaillau in https://github.com/control-toolbox/CTBase.jl/pull/150#discussion_r1635519354_

**Comment by jbcaillau** [comment]
Maybe not instead but in addition to. (Compatibility...)

**Comment by jbcaillau** [comment]
Right. We still have to choose one possibility among the two for the alias (either `ctVector` or `NonFixed`). I tend to think that the type of a variable should be `ctVector` but I remember that the state and costate also have aliases (towards `ctVector`). Bref.

**Comment by PierreMartinon** [comment]
We could rename *Variable* to *OptimVariable* or something ?

**Comment by jbcaillau** [comment]
Yes, while this will break the current convention for our types. Let's keep it like this for now, as there are things to might change for `State` (might include matrix type) and `Costate` (might be covector). 
> We could rename _Variable_ to _OptimVariable_ or something ?
