### ISSUE TITLE
v0.9.1 ?

### ISSUE THREAD

**Issue by PierreMartinon** [control-toolbox/CTBase.jl#152]
Hi @ocots,
The repo shows 0.9.0 as latest release, however I get 0.9.1 from the registry, and it seems to have broken something for me
```
  LoadError: UndefVarError: `__OCPModel` not defined
```
coming from this abstract definition (tf line)
```
@def ocp1 begin
    tf ∈ R, variable
    t ∈ [ 0, tf ], time
    x ∈ R², state
    u ∈ R, control
    -1 ≤ u(t) ≤ 1
    x(0) == [ 0, 0 ]
    x(tf) == [ 1, 0 ]
    0.1 ≤ tf ≤ Inf 
    ẋ(t) == [ x₂(t), u(t) ] 
    tf → min
end
```

My problem is that I can't find a way to force 0.9.0: for 0.x.y versions the tilde and caret are treated the same in [compat] entries, and all y versions are assumed compatible.

Maybe we should move to 1.0.0 on all packages to have the standard compat behaviour ?

**Comment by jbcaillau** [comment]
@PierreMartinon OMG le gamin a encore tout pété 🤯 !!!

**Comment by ocots** [comment]
Here 

https://github.com/control-toolbox/CTDirect.jl/blob/ddba4dec8e6ee88e4a226729f187ba130d08af8b/src/CTDirect.jl#L41

You have to replace by

```julia
export Model, __OCPModel
```

**Comment by ocots** [comment]
Are we ok that you have a problem when using `CTDirect`?

**Comment by ocots** [comment]
Actually, I don't understand why you reexport all these functions from `CTBase` in the `CTDirect` package.

**Comment by ocots** [comment]
> @PierreMartinon OMG le gamin a encore tout pété 🤯 !!!

Exactement. En fait, si on utilise un autre package qui a une méthode `Model`, comme `JuMP` par exemple, ça pose problème. C'est ce que l'on fait actuellement pour du benchmarking. Il faut en principe "qualifier" l'appel à la méthode : 

```julia
JuMP.Model()
OptimalControl.Model()
```

Cependant, comme la macro `@def` se trouve dans `CTBase`, si on fait appel à la macro depuis `CTBase` il faudrait pour l'appel à `Model` faire : 

```julia
CTBase.Model()
````

mais si on est en train d'utiliser `OptimalControl` qui lui-même exporte `@def`, il faudrait dans la macro que le code généré fasse l'appel 

```julia
OptimalControl.Model()
````

Du coup, ce n'est pas gérable ainsi. J'ai préféré crée une fonction interne avec un nom assez spécifique qui posera pas de soucis, c'est pourquoi j'ai ajouté `__OCPModel` qui est une simple redirection vers `Model`. 

Cependant, pour que `@def` fonctionne, il faut maintenant exporter à la fois `Model` et `__OCPModel`. A voir si on peut faire un truc plus propre.

**Comment by PierreMartinon** [comment]
> Here:
> 
> [control-toolbox/CTDirect.jl@`ddba4de`/src/CTDirect.jl#L41](https://github.com/control-toolbox/CTDirect.jl/blob/ddba4dec8e6ee88e4a226729f187ba130d08af8b/src/CTDirect.jl#L41)
> 
> You have to replace `export Model` by
> 
> ```julia
> export Model, __OCPModel
> ```
> 
> Are we ok that you have a problem when using `CTDirect`? If the problem comes from `OptimalControl`, be sure you have the version `0.8.2`.
> 
> Actually, I don't understand why you reexport all these functions from `CTBase` in the `CTDirect` package.


All working again with the added export, thanks ! CTDirect 0.6.1 on its way. As for the exports, I was just lazy to retype CTBase, but maybe those are not necessary anymore, I'll review them :D

Maybe we should add a basic test for the abstract formulation in OptimalControl ?

Note: regarding version numbers, the convention for 0.x.y packages is apparently to bump x in case of non-backwards compatibility, since the specific behaviour of [compat] for 0. does not allow to fix a single 0.x.y version.

**Comment by ocots** [comment]
> All working again with the added export, thanks ! CTDirect 0.6.1 on its way. As for the exports, I was just lazy to retype CTBase, but maybe those are not necessary anymore, I'll review them :D

I don't really have a clear idea about the following. When using `OptimalControl` we do not want the user to import also `CTBase` and `CTDirect` so we export needed functions from these two packages. When using `CTDirect`, event if `CTBase` is at a lower level in terms of software architecture, I am wondering if we must export some functions or simply if we expect that the user simply import both packages:

```julia
using CTBase
using CTDirect
@def ocp begin
...
end
solve(ocp)
```

For me it is clearer like this and when using `OptimalControl` with simply have

```julia
using OptimalControl
@def ocp begin
...
end
solve(ocp)
```

which contains both packages. In that case, it seems that `CTDirect` has no reason to export any functions from `CTBase`.

> 
> Maybe we should add a basic test for the abstract formulation in OptimalControl ?
> 

I think there is a test in `OptimalControl`. I will check this.

> Note: regarding version numbers, the convention for 0.x.y packages is apparently to bump x in case of non-backwards compatibility, since the specific behaviour of [compat] for 0. does not allow to fix a single 0.x.y version.

Since I haven't modified the usage of the macro `@def` I thought it would not break anything but this was a mistake. However, I don't really like the solution I have found to handle this problem of "qualified calls" when we you another package that contains a function `Model`, because `__OCPModel` has to be internal and should not be exported...

**Comment by jbcaillau** [comment]
@ocots @PierreMartinon I agree that:
- an internal such as `__OCPModel` should not be exported
- this bizarrerie is just an outcome of the relevant point about having as many `Model` types as used modules, which is absolutely normal (then prexifing / qualifying by the module name is the rule)
- regarding `@def`, I don't see why prefixing would not solve the problem, but I'm probably missing sth here
- regarding our modules (packages...) hierarchy, I also advocate the fact that the user wants to be `using OptimalControl`, nothing else (not even `CTDirect`, and obviously not `CTBase`)

**Comment by PierreMartinon** [comment]
I'm fine with your view on using / exports. Updated in upcoming 0.6.1

Not familiar enough with macros to have any insight on the def prefixing thing. Not having to prefix is convenient, although it would not be a huge burden.
