### ISSUE TITLE
Suppress Index in constraints

### ISSUE THREAD

**Issue by jbcaillau** [control-toolbox/CTBase.jl#155]
... but keep for (variable) times
![IMG_3235](https://github.com/control-toolbox/CTBase.jl/assets/62183989/b7accf78-ff36-4860-b085-9a5fe4f1d135)

**Comment by PierreMartinon** [comment]
Can you elaborate please :D ?

**Comment by PierreMartinon** [comment]
Hi @ocots @jbcaillau 
What is the new syntax for a basic initial condition x(t0) = x0 ?
```
ocp = Model(variable=true)
state!(ocp, 3)
control!(ocp, 1)
variable!(ocp, 1)
time!(ocp, t0=0, indf=1)
constraint!(ocp, :initial, [1,0,1], :initial_constraint)
```

**Comment by PierreMartinon** [comment]
Ok, so basically everything after the constraint type is now a named argument.

**Comment by PierreMartinon** [comment]
Another question @ocots :D
On the goddard problem, the following box constraint is fine
```
constraint!(ocp, :state, lb=[r0,v0,mf], ub=[r0+0.2,vmax,m0])
```
while the functional version fails (restoration error at first iteration)
```
constraint!(ocp1, :state, f=(x,v)->x, lb=[r0,v0,mf], ub=[r0+0.2,vmax,m0])
```
I tried splitting in 3 separate constraints, same problem. Did I miss something ?

**Comment by jbcaillau** [comment]
@PierreMartinon there is a difference (that should not suffice to alter solving, though) as
- in the first case I suppose that the range is implemented as a box constraint in `CTDirect.jl`
- while in the second case, a genuine (functional) constraint is added

Note that while the first syntax is allowed, it is more readable to write
```julia
constraint!(ocp, :state; rg=1:end, lb=[r0,v0,mf], ub=[r0+0.2,vmax,m0])
```

Currently fixing [a few things](https://github.com/control-toolbox/CTBase.jl/pull/165) in the `constraint!` function 🤞🏾

**Comment by PierreMartinon** [comment]
Yup. As I said, not a blocking issue, I'm just trying to figure out the different possibilities.
I'll try to look more closely at the actual constraints in the defined ocp

**Comment by jbcaillau** [comment]
> Yup. As I said, not a blocking issue, I'm just trying to figure out the different possibilities. I'll try to look more closely at the actual constraints in the defined ocp

@PierreMartinon please drop a pointer towards the example not converging with
```julia
constraint!(ocp1, :state, f=(x,v)->x, lb=[r0,v0,mf], ub=[r0+0.2,vmax,m0])
```

**Comment by PierreMartinon** [comment]
Here you go. The one below converges
```
# general definitions
Cd = 310
Tmax = 3.5
β = 500
b = 2
r0 = 1
v0 = 0
vmax = 0.1
m0 = 1
mf = 0.6
x0 = [ r0, v0, m0 ]
function F0(x)
    r, v, m = x
    D = Cd * v^2 * exp(-β*(r - 1))
    return [ v, -D/m - 1/r^2, 0 ]
end
function F1(x)
    r, v, m = x
    return [ 0, Tmax/m, -b*Tmax ]
end

# box constraints
ocp = Model(variable=true)
state!(ocp, 3)
control!(ocp, 1)
variable!(ocp, 1)
time!(ocp, t0=0, indf=1)
constraint!(ocp, :initial, lb=x0, ub=x0)
constraint!(ocp, :final, rg=3, lb=mf, ub=Inf)
constraint!(ocp, :state, lb=[r0,v0,mf], ub=[r0+0.2,vmax,m0])
constraint!(ocp, :control, lb=0, ub=1)
constraint!(ocp, :variable, lb=0.01, ub=Inf)
objective!(ocp, :mayer, (x0, xf, v) -> xf[1], :max)
dynamics!(ocp, (x, u, v) -> F0(x) + u*F1(x) )

sol = solve(ocp, grid_size=100, print_level=0, tol=1e-8)
```

**Comment by PierreMartinon** [comment]
Ok, with Joseph we may have found the answer: ipopt will internally project the initial guess inside the variable bounds if needed. Here for instance the default init (0.1) will be projected for both r and m.

When using a functional (nonlinear) constraint, there is no such initial guess adjustment, and for this problem in particular, having r<1 (earth radius) is known to be problematic.

I'll recheck with a more sensible initial guess and see if the functional constraint converges.

**Comment by jbcaillau** [comment]
@PierreMartinon @joseph-gergaud nice! indeed, not having a box prevents `Ipopt` from making this educated guess.

**Comment by PierreMartinon** [comment]
Confirmed, we get the convergence back when initializing the state with r>1. No more remarks for me here, you can close when you want.

**Comment by ocots** [comment]
Please review what is done: 

- [ ] suppress index in constraints
- [ ] add in the doc for the constraints at least one equality constraint example, cf. [here](https://github.com/control-toolbox/CTBase.jl/issues/155#issuecomment-2182330173)

**Comment by jbcaillau** [comment]
@ocots closed 

> @jbcaillau Please review what is done:
> 
> * [x]  suppress index in constraints
> * [ ]  add in the doc for the constraints at least one equality constraint example, cf. [here](https://github.com/control-toolbox/CTBase.jl/issues/155#issuecomment-2182330173)

closed in favour of https://github.com/control-toolbox/OptimalControl.jl/issues/155
