### ISSUE TITLE
error in docstring 

### ISSUE THREAD

**Issue by joseph-gergaud** [control-toolbox/CTBase.jl#16]
@jbcaillau 

I think that there is  an error in
 https://github.com/control-toolbox/CTBase.jl/blob/main/src/model.jl#L171 

solution : 
```julia
"""
julia> constraint!(ocp, :final, 0, 2)
julia> constraint!(ocp, :control, 0, 2)
"""
```

**Comment by jbcaillau** [comment]
@joseph-gergaud Hi! Can't see this line. Can you please:
- tell me where this is in the `parser` branch version of [model.jl](https://github.com/control-toolbox/CTBase.jl/blob/parser/src/model.jl)
- be more precise (error in *just* in docstring)?

**Comment by jbcaillau** [comment]
@joseph-gergaud Clear: right, please merge [this PR](https://github.com/control-toolbox/CTBase.jl/pull/17)
