### ISSUE TITLE
Update nlp_constraints to nlp_constraints!

### ISSUE THREAD

**Issue by jbcaillau** [control-toolbox/CTBase.jl#167]
@PierreMartinon add a side effect on `ocp` to store constraints dimensions. Also redefine associated getters. The new `nlp_constraints!` will serve as a setter (*one computation to set them all*).

**Comment by PierreMartinon** [comment]
You lost me there oO 

When I introduced the getters, I computed the dimensions at the end of *nlp_constraints*.
It worked, but as Olivier pointed out, not very clean. I believe he had started a better version with updates at each *constraint* call ?

As for CTDirect, I am fine with either. Before we introduced the getters, I used to take the dimensions from the ouptut of *nlp_constraints* anyway.

Just tell me if you change the interface ;-)

**Comment by jbcaillau** [comment]
> You lost me there oO 
> 
> When I introduced the getters, I computed the dimensions at the end of *nlp_constraints*.
> 
> It worked, but as Olivier pointed out, not very clean. I believe he had started a better version with updates at each *constraint* call ?

I was not happy with that. Changed it, and at the same time updated the build of the constraint functions (allocations instead of `push`es). 

> As for CTDirect, I am fine with either. Before we introduced the getters, I used to take the dimensions from the ouptut of *nlp_constraints* anyway.
> 
> 
> 
> Just tell me if you change the interface ;-)

Almost nothing. Coming next
