### ISSUE TITLE
Update doc

### ISSUE THREAD

**Issue by ocots** [control-toolbox/CTBase.jl#172]
https://github.com/control-toolbox/CTBase.jl/blob/d2aa9b48ef2a799e921d7fc1e49276ef8b2c64ce/src/init.jl#L16

The kwarg in the docstrings are not good. Actually `x_init` must be replaced by `state`.

**Comment by ocots** [comment]
Add also in `CTBase.jl` documentation the doc of `OptimalControlInit`.

**Comment by jbcaillau** [comment]
@PierreMartinon And same comment as in XXXX: would be better to stick to [Julia blue style](https://github.com/JuliaDiff/BlueStyle) for naming: `optimal_control_init`, or simply `init`. The shorter, the better, I would say. Thanks to multiple dispatch, such things as `init`, `solve`, `plot`... should be possible 🤞🏽.

**Comment by ocots** [comment]
OptimalControlInit is a type. It is internal.

**Comment by jbcaillau** [comment]
> OptimalControlInit is a type. It is internal.

OK. type constructor, then ✅

**Comment by PierreMartinon** [comment]
The initialization part spans across different packages and we're still adding features, so it has evolved quite a bit and is not yet solidified, so to speak.

Regarding style guides, blue is not the only one, see https://discourse.julialang.org/t/is-there-a-julia-style-guide/80195/3
We can take the time to choose the one we like best.

**Comment by ocots** [comment]
This is related to https://github.com/control-toolbox/CTBase.jl/issues/173.

**Comment by ocots** [comment]
Done with https://github.com/control-toolbox/CTBase.jl/pull/184
