### ISSUE TITLE
Initialise from a vector of points

### ISSUE THREAD

**Issue by ocots** [control-toolbox/CTBase.jl#173]
For the moment, we can initialise 

- with constants
- with functions of time
- with a solution

but we cannot provide a vector of points at the points of the grid. We should add this.

**Comment by jbcaillau** [comment]
@ocots @PierreMartinon Yes. Similar to https://github.com/control-toolbox/CTDirect.jl/issues/112. [^1] Since it is already possible to initialise with
- state and control functions
- a non-uniform time grid

things should be pretty much OK already.

[^1]: Regarding initialisations, please clarify what should be in `CTBase.jl` or `CTDirect.jl`.

**Comment by PierreMartinon** [comment]
Ok, this just popped up in the shuttle problem.
Also, it seems we don't give warnings when arguments with incorrect names are given (which ends up with default initialisation)
I can start a branch for this, unless someone else wants to do it ?

**Comment by jbcaillau** [comment]
@PierreMartinon feel free to take care of it 🙂: here is the branch (in `CTDirect.jl`, not `CTBase.jl`):

https://github.com/control-toolbox/CTDirect.jl/tree/173-initialise-from-a-vector-of-points


I suggest to close https://github.com/control-toolbox/CTDirect.jl/issues/112 which is more or less the same thing.

**Comment by PierreMartinon** [comment]
Ok I'll give it a try. Initialization is in CTBase though, not in CTDirect :D

**Comment by PierreMartinon** [comment]
PS. Although I can try a version in CTDirect that would shadow the one in CTBase.

**Comment by jbcaillau** [comment]
🙏🏽 @PierreMartinon branch + https://github.com/control-toolbox/CTBase.jl/pull/175 you're in control 🙂

> Ok I'll give it a try. Relevant part is in _CTBase_ though, not in _CTDirect_ :D
> 
> More precisely, defining a functional initial guess for the OCP is in _CTBase_, whatever the inputs (constants, functions, solutions, matrices ...). This common data is then used by each method to generate their own specific initial guess, provided the required info is there (for instance for an indirect method you would need the costate information)
> 
> What remains in _CTDirect_ is building the actual finite dimensional initial guess X_0 for the NLP problem.

**Comment by PierreMartinon** [comment]
Ok, a first version seems to work https://github.com/control-toolbox/CTDirect.jl/tree/local_init

- new code is in src/utils.jl, defining _OptimalControlInit and related functions as a replacement of the OptimalControlInit from CTBase
- some code factorization (state and control have similar handling, warm start reuses base constructor)
- error message for unrecognized keys, and some missing cases (eg. passing a matrix without the time vector)
- initialization with matrices (time_steps x state|control_dimension), with an additional argument time=<time_vector>. This will reuse ctinterpolate internally.

**Comment by PierreMartinon** [comment]
The relevant code
```
# local init
function setFunctionalInit(data, time)
    if isnothing(data)
        return t-> nothing
    elseif data isa Function
        return t -> data(t)
    elseif (data isa ctVector)
        if isnothing(time)
            return t -> data
        else
            itp = ctinterpolate(time, data)
            return t -> itp(t)
        end
    elseif data isa Matrix
        if isnothing(time)
            error("Matrix initialization also requires the time vector. Got ", time)
        else
            itp = ctinterpolate(time, matrix2vec(data, 1))
            return t -> itp(t)
        end
    end

end

mutable struct _OptimalControlInit
   
    state_init::Function
    control_init::Function
    variable_init::Union{Nothing, ctVector}
    costate_init::Function
    multipliers_init::Union{Nothing, ctVector}

    # base constructor with explicit arguments
    function _OptimalControlInit(; state::Union{Nothing, ctVector, Function, Matrix}=nothing, control::Union{Nothing, ctVector, Function, Matrix}=nothing, variable::Union{Nothing, ctVector}=nothing, time::Union{Nothing, ctVector}=nothing)
        
        init = new()
        init.state_init = setFunctionalInit(state, time)
        init.control_init = setFunctionalInit(control, time)
        init.variable_init = variable
        return init

    end

    # version with arguments as named tuple or dict
    function _OptimalControlInit(init_data)

        x_init = nothing
        u_init = nothing
        v_init = nothing
        t_init = nothing

        for key in keys(init_data)
            if key == :state
                x_init = init_data[:state]
            elseif key == :control
                u_init = init_data[:control]
            elseif key == :variable
                v_init = init_data[:variable]
            elseif key == :time
                t_init = init_data[:time]
            else
                error("Unknown key in initialization data (allowed: state, control, variable, time): ", key)
            end
        end

        return _OptimalControlInit(state=x_init, control=u_init, variable=v_init, time=t_init)
    
    end

    # warm start from solution
    function _OptimalControlInit(sol::OptimalControlSolution)
        return _OptimalControlInit(state=sol.state, control=sol.control, variable=sol.variable)
    end

    # trivial version for unified syntax in caller functions
    function _OptimalControlInit(init::_OptimalControlInit)
        return init
    end

end
```

**Comment by PierreMartinon** [comment]
@ocots @jbcaillau I'll wait a bit before working on the CTBase branch. Comments / suggestions welcome, for instance on the ambiguous vector case

**Comment by jbcaillau** [comment]
thanks @PierreMartinon *As a user* 🙂 is would be nice to be able to initialise control and state [^1] passing:
- a function (of time)
- a single (vector) value
- a vector of (vector) values [^2]
- a previous sol (warm start) [^3]

In parallel, the user chooses a time grid (uniform - default - or not), so everything has to match. Obviously:
- once `t_grid` is fixed, everything falls back to the function case (not so efficient to interpolate to reevaluate on the same grid but almost costless)
- in case of a vector of values, just check the length is the same as for `t_grid`


NB. @ocots I haven't checked what you use for `ctinterpolate` but there are nice packages that do the job, *e.g.* [Interpolations.jl](https://github.com/JuliaMath/Interpolations.jl).

[^1]: the variable case is trivial, just a single (scalar / vector) value

[^2]: Julia style is more on vector of vectors (`x_init[1]` having length `dim_state`) than matrices, but both are acceptable

[^3]: though this is very easily obtained from getters on the solution, it is still convenient in simple case, *e.g.* for grid refinement

**Comment by PierreMartinon** [comment]
Reformatting
```
t_grid = [0 .1 1] # Normalised
x_fun(t) = [t, t^2]
x = [ .5, 1 ]
x_grid = [[0, 0], [1, 2], [5, -1]]
u_fun(t) = 2t - 1
u = 2
u_grid = [0, 3, .1]
v = [1]
N = 400
```
Use cases
- [ ] ```sol = solve(ocp, init=(time=t_grid, state=x_grid, control=u_fun, variable=v))```
- [ ] ```sol = solve(ocp, init=(grid_size=N, state=x_fun, control=u_grid))```
- [ ] ```sol = solve(ocp, init=(state=x, control=u_grid)) # Default uniform time grid (N = 100)```
- [ ] ```sol = solve(ocp, init=(state=x_fun, control=u))```
- [ ] ```sol = solve(ocp, init=sol, grid_size=N)```

**Comment by jbcaillau** [comment]
@PierreMartinon 

> See test: https://github.com/control-toolbox/CTDirect.jl/blob/local_init/test/test_initial_guess_local.jl
> 
> A few remarks
> 
> * the call to _Init()_ is optional, meaning you can already pass _init=sol_ or _init=(state=...,)_. The idea is to keep the constructor internal if possible.
> * if no explicit time grid is passed, the best we can do is take a uniform normalized grid with default grid_size, whcih is kind of limited. On the other hand, generating the wanted time grid should be pretty trivial. Time grid can be passed as a vector or matrix (ie blank separators)
> * for interpolation, both vectors of vectors and matrices are (or at least should be) supported, with vectors also supported for dimension 1 variables. Ambiguity vs constant initialization is resolved by checking vector length.
> 
> Problem: double integrator for instance, free final time, min tf
> 
> ```
> @def ocp begin
>     tf ∈ R, variable
>     t ∈ [ 0, tf ], time
>     x ∈ R², state
>     u ∈ R, control
>     -1 ≤ u(t) ≤ 1
>     x(0) == [ 0, 0 ]
>     x(tf) == [ 1, 0 ]
>     0.1 ≤ tf ≤ Inf 
>     ẋ(t) == [ x₂(t), u(t) ] 
>     tf → min
> end
> ```
> 
> Context
> 
> ```
> t_grid = [0, .1, 1]
> t_matrix = [0 .1 1]
> x_fun(t) = [t, t^2]
> #x = [ .5, 1 ]
> x_matrix = [0 0; 1 2; 5 -1]
> x_grid = [[0, 0], [1, 2], [5, -1]]
> u_fun(t) = 2t - 1
> u = 0.7 # will be projected inside [-1,1] bounds
> #u_grid = [0, 3, .1]
> v = 1
> N = 400
> ```
> 
> Use cases
> 
> * [x]  `sol = solve(ocp, init=(time=t_grid, state=x_grid, control=u_fun, variable=v))`
> * [x]  `sol = solve(ocp, init=(time=t_matrix, state=x_grid, control=u_fun, variable=v))`
> * [x]  `sol = solve(ocp, init=(time=t_grid, state=x_matrix, control=u_fun, variable=v))`
> * [x]  `sol = solve(ocp, init=(time=t_matrix, state=x_matrix, control=u_fun, variable=v))`
> * [ ]  `sol = solve(ocp, init=(grid_size=N, state=x_fun, control=u_grid))`
>   **I don't think I understand this one: u_grid is of length 3 and can't really be interpolated against a time grid of length 400. Or maybe you meant the 'destination' grid size ? We always return functions in the init so there is no time grid in the output**

Ouh! Made a big 💩💩 here, you're right. Should error.

> * [ ]  `sol = solve(ocp, init=(state=x, control=u_grid)) # Default uniform time grid (N = 100)`
>   **same question here**

Again 😱!

> * [x]  `sol = solve(ocp, init=(state=x_fun, control=u))`
> * [x]  `sol = solve(ocp, init=sol, grid_size=N)`

**Comment by PierreMartinon** [comment]
Currently, expanding the arguments *state, control, variable* is not supported. Adding it may be possible but there would be several ambiguous cases to handle: mutually eclusive with *init=*, and *time* for init vs *time_grid* for solve. For now I think it's easier to keep the intialization data packed as a single argument (which can already take quite a number of different forms).

Also, a current limitation is that the init structure has no knowledge of the supposed dimensions for x,u,v, so it cannot check that the vectors/matrices have the correct size. Adding them would complicate the constructor calls though. Maybe I can make them optional and fill them when the information is available at the call. I'll see.

**Comment by jbcaillau** [comment]
@PierreMartinon Good. Note that it's very convenient to use [pattern matching](https://thautwarm.github.io/MLStyle.jl/latest/syntax/pattern.html#pattern-matching) to test (combination) of arguments.

PR soon?

**Comment by jbcaillau** [comment]
@PierreMartinon In accordance with comments below (init in `CTBase.jl`), can you please move what you did in https://github.com/control-toolbox/CTDirect.jl/tree/local_init to a branch in `CTBase.jl` and PR when ready?

> 🙏🏽 @PierreMartinon branch + #175 You're in control 🙂
> 
> Closing [control-toolbox/CTDirect.jl#112](https://github.com/control-toolbox/CTDirect.jl/issues/112)
> 
> > Ok I'll give it a try. Relevant part is in _CTBase_ though, not in _CTDirect_ :D
> > More precisely, defining a functional initial guess for the OCP is in _CTBase_, whatever the inputs (constants, functions, solutions, matrices ...). This common data is then used by each method to generate their own specific initial guess, provided the required info is there (for instance for an indirect method you would need the costate information)
> > What remains in _CTDirect_ is building the actual finite dimensional initial guess X_0 for the NLP problem.

**Comment by ocots** [comment]
We must warn the user if a wrong keyword is given: see https://github.com/control-toolbox/CTBase.jl/issues/174.

**Comment by ocots** [comment]
The docstrings must be updated: see https://github.com/control-toolbox/CTBase.jl/issues/172.

**Comment by jbcaillau** [comment]
@ocots is this related to #173?

**Comment by PierreMartinon** [comment]
Current state:
- API mostly unchanged, except that _OptimalControlInit is now internal (ie the constructor is not supposed to be called explicitely by the user)
- error messages for unrecognized keywords
- dimension checks for state, control and variable
- allow initialization by interpolating a matrix or vect{vect} **with the corresponding time grid** (no longer optional)
- code uses multiple dispatch for the various initialization formats, so extensions should be easier

I still need to update the DOCSTRINGS and the CI tests (checking the objective is trivial since we always get convergence, and iterations are not reliable. I'll probably check final state and control using max_iter=0).

I'll make the PR after these 2 points, but don't hesitate if you already have comments.

**Comment by PierreMartinon** [comment]
Ok, tests updated, and some docstrings updates as well.
@ocots , did you have any problems with Documenter and the package extensions ? In *CTDirect* I had to manually add docs blocks for extended functions, and *solve* still does not show up, probably because I extend a function from *CommonSolve* and not *CTDirect*. Maybe I'll have to add an empty *solve* in *CTDirect* finally...

**Comment by ocots** [comment]
Actually, I do not manage to have the docstrings of extended functions. I have the same problem as you. Maybe we should put in the `src` folder:

```julia
""" docstrings
function my_function_to_be_extended
```

and then extend the function in the extension.

**Comment by jbcaillau** [comment]
@PierreMartinon trying to test everything (initialisations + other changes in `CTBase.jl`, `CTDirect.jl` and `CTFlows.jl`, using the latest tags). We agree that everything has been merged in `main`?

**Comment by ocots** [comment]
Done in https://github.com/control-toolbox/CTBase.jl/pull/184
