### ISSUE TITLE
Add a message

### ISSUE THREAD

**Issue by ocots** [control-toolbox/CTBase.jl#174]
https://github.com/control-toolbox/CTBase.jl/blob/d2aa9b48ef2a799e921d7fc1e49276ef8b2c64ce/src/init.jl#L60

Add a message when a key is given but has no meaning.

**Comment by ocots** [comment]
This is related to https://github.com/control-toolbox/CTBase.jl/issues/173.

**Comment by jbcaillau** [comment]
This is related to #173 🤭

**Comment by ocots** [comment]
Done with https://github.com/control-toolbox/CTBase.jl/pull/184
