### ISSUE TITLE
pb with constraint!

### ISSUE THREAD

**Issue by joseph-gergaud** [control-toolbox/CTBase.jl#18]
@jbcaillau 

For testing Direct method for optimal control problem with box constraints on the control I add the constraint 
```math
|u|\leq 5
```
for the intretrator problem. For this I write : 
constraint!(ocp, :control, -5, 5, :control_con1) and I have the following error : 
ERROR: LoadError: the following type of constraint is not valid: control. Please choose in [ :initial, :final ] or check the arguments of the constraint! method.
Stacktrace:
 [1] constraint!(ocp::OptimalControlModel{:autonomous, :scalar}, type::Symbol, rg::Int64, val::Int64, label::Symbol)
   @ CTBase ~/.julia/packages/CTBase/MH2ax/src/model.jl:158
 [2] top-level scope
   @ ~/control-toolbox/CTDirect.jl/test/test_direct_infos.jl:43
 [3] include(fname::String)
   @ Base.MainInclude ./client.jl:476
 [4] top-level scope
   @ ~/control-toolbox/CTDirect.jl/test/runtests.jl:7
 [5] include(fname::String)
   @ Base.MainInclude ./client.jl:476
 [6] top-level scope
   @ none:6
in expression starting at /Users/gergaud/control-toolbox/CTDirect.jl/test/test_direct_infos.jl:43
in expression starting at /Users/gergaud/control-toolbox/CTDirect.jl/test/runtests.jl:7
ERROR: Package CTDirect errored during testing

But if I  write 
constraint!(ocp, :control, -5., 5., :control_con1)

it's ok

Thee problem is that in the first case the constants are Int and in the second case there  are Float.

**Comment by jbcaillau** [comment]
Right. When typed as `Int`, the value is used as an index (particular case of a range). This is because we authorise not to give the range (which means *full range*). Thinking over it. Right now, please enforce `Real` for bounds.

**Comment by jbcaillau** [comment]
@joseph-gergaud proposed solution in [this PR](https://github.com/control-toolbox/CTBase.jl/pull/22)
