### ISSUE TITLE
Add init unit tests

### ISSUE THREAD

**Issue by ocots** [control-toolbox/CTBase.jl#187]

**Comment by jbcaillau** [comment]
@PierreMartinon can you please confirm that init in `CTBase.jl` is OK? (apart maybe from some doc stuff)

The case being, everything but doc should be ready to release `OptimalControl 1.0` with latest `CTxxxx.jl` versions (extensions, mostly).

**Comment by PierreMartinon** [comment]
Well, all tests seem fine. By the way you can use () or nothing for default init, both work.

Unit tests in CTBase are a good idea, we would just call the constructor and check the resulting init functions against the source data. Need to write some methods that compare a function to i) a constant ii) a function iii) a vector with its time grid.

**Comment by ocots** [comment]
Can we close?

**Comment by jbcaillau** [comment]
> Can we close?

@PierreMartinon

**Comment by PierreMartinon** [comment]
Tests still need to be updated in OptimalControl, I recently updated the tests in CTDirect to a closer syntax to make the import easier.
I guess I'll complete some tests in the next PR for OptimalControl (the one to match the future CTDirect 0.10.0).
