### ISSUE TITLE
Go to general registry 🤞 

### ISSUE THREAD

**Issue by ocots** [control-toolbox/CTBase.jl#194]
- [TagBot](https://github.com/JuliaRegistries/TagBot)
- [Install app](https://github.com/JuliaComputing/Registrator.jl?tab=readme-ov-file#install-registrator)
- Comment this issue following [this](https://github.com/JuliaComputing/Registrator.jl?tab=readme-ov-file#via-the-github-app)

**Comment by ocots** [comment]
@JuliaRegistrator register()

**Comment by ocots** [comment]
The name is too close to existing ones.

See [this](https://juliaregistries.github.io/RegistryCI.jl/stable/guidelines/#Name-similarity-distance-check) to evaluate distances.

**Comment by ocots** [comment]
@jbcaillau @PierreMartinon @joseph-gergaud we need to change the name.

**Comment by jbcaillau** [comment]
@ocots 💩
- `OCBase.jl` would have the same problem, I guess; and not so coherent *wrt.* `CT` / the org. name
- `ControlToolboxBase.jl` is a bit long, but makes sense / is systematic (and only internal, as no user will refer to it)

**Comment by jbcaillau** [comment]
@ocots @PierreMartinon @joseph-gergaud actually, I guess it would be possible to keep the `CTxxxx.jl` packages in our own registry to avoid this. Since the user is only supposed to use `OptimalControl.jl`, this would make sense.

**Comment by ocots** [comment]
> @ocots @PierreMartinon @joseph-gergaud actually, I guess it would be possible to keep the `CTxxxx.jl` packages in our own registry to avoid this. Since the user is only supposed to use `OptimalControl.jl`, this would make sense.

I guess not since then the user will have to add ct registry to install depedencies. It could be nice to install simply with `add OptimalControl`.

**Comment by jbcaillau** [comment]
@ocots we can probably put a `Pkg.Registry.add(...)` somewhere 🫢

**Comment by ocots** [comment]
We may have not to change the name since it has been accepted: https://github.com/JuliaRegistries/General/pull/110480#issuecomment-2210625065.

**Comment by ocots** [comment]
I don't understand why auto-merge is not working. See https://github.com/JuliaRegistries/General/pull/110480

I have put [noblock] in the comment :-(

**Comment by PierreMartinon** [comment]
Congrats by the way. Getting official !

**Comment by ocots** [comment]
Not yet.

**Comment by PierreMartinon** [comment]
> Your new package registration met all of the guidelines for auto-merging and is scheduled to be merged when the mandatory waiting period (3 days) has elapsed.

So we just have to wait I guess ?

**Comment by ocots** [comment]
I don't know what we have to do 😮‍💨

**Comment by ocots** [comment]
For research gate im ok

**Comment by PierreMartinon** [comment]
> I don't know what we have to do 😮‍💨

I think we just have to wait the 3 days

**Comment by PierreMartinon** [comment]
> For research gate im ok

Oh well, https://www.researchgate.net/researchgate-updates/retiring-projects

**Comment by jbcaillau** [comment]
@PierreMartinon @ocots @joseph-gergaud hi
- yes, "mandatory waiting period (3 days)". @ocots to be ready for next Wednesday, we need to submit all the packages asap: can you please take care of it?
- not a big fan of ResearchGate: private business, not very reliable

I'd rather advocate a [Zenodo](https://zenodo.org) deposit + a [JOSS](https://joss.theoj.org/) paper.

**Comment by PierreMartinon** [comment]
> @PierreMartinon @ocots @joseph-gergaud hi
>     * not a big fan of ResearchGate: private business, not very reliable

Well, putting a few sentences and a link on researchgate, linkedin etc always help to promote the software, and it doesn't bind us to the platforms.

Don't know zenodo/joss, any experience with them ?

**Comment by jbcaillau** [comment]
@PierreMartinon https://github.com/control-toolbox/OptimalControl.jl/issues/175
> > Don't know zenodo/joss, any experience with them ?
> 
> * Zenodo is the reference for such deposits, public and maintained by CERN
