### ISSUE TITLE
No aggregation anymore

### ISSUE THREAD

**Issue by ocots** [control-toolbox/CTBase.jl#197]
Add the top menu directly into the doc of the package.

**Comment by jbcaillau** [comment]
@ocots right now, no more menu showing up on my phone. we need to think and check on mobile devices once it s stabilised. 

![IMG_9626](https://github.com/user-attachments/assets/944e2c65-d888-4b1f-9193-7c87a00bd224)

**Comment by ocots** [comment]
I know. I work on that but i have to check-in.

**Comment by ocots** [comment]
This can be fixed without re-doing any doc. Just one file to fiix.
