### ISSUE TITLE
Equality constraint

### ISSUE THREAD

**Issue by ocots** [control-toolbox/CTBase.jl#204]
> You are right we have removed this possibility. We consider that the abstract form is the standard and we have reduced the number of different signatures for the functional form. However, we could have a keyword `val` replacing the `lb` and `ub` keywords.

_Originally posted by @ocots in https://github.com/control-toolbox/OptimalControl.jl/issues/155#issuecomment-2230299701_

**Comment by ocots** [comment]
@jbcaillau Do we add a keyword `val` which means that `lb = ub = val`?

**Comment by jbcaillau** [comment]
yes we can 🙂 help yourself mr cots!

**Comment by ocots** [comment]
When done, update https://control-toolbox.org/OptimalControl.jl/stable/tutorial-basic-example-f.html.
