### ISSUE TITLE
Preparing for inplace NLP

### ISSUE THREAD

**Issue by jbcaillau** [control-toolbox/CTBase.jl#232]
@PierreMartinon aiming to providing inplace function as a result of `nlp_constraints!`, having inplace signatures for `ξ, η, ψ, ϕ, θ`: 
```julia
julia> (ξl, ξ, ξu), (ηl, η, ηu), (ψl, ψ, ψu), (ϕl, ϕ, ϕu), (θl, θ, θu),
    (ul, uind, uu), (xl, xind, xu), (vl, vind, vu) = nlp_constraints!(ocp)
```

Related to: https://github.com/control-toolbox/CTDirect.jl/issues/188

@ocots I'll need some help to update the unit tests.

**Comment by jbcaillau** [comment]
@jbcaillau 5 possible nonlinear (= defined by functions, now inplace) constraints to treat, associated respectively with `ξ, η, ψ, ϕ, θ`:
```julia
        (type, f::BoundaryConstraint, lb, ub) && if type ∈ [:initial, :final, :boundary] end # ϕ
        (:control, f::ControlConstraint, lb, ub) # ξ
        (:state, f::StateConstraint, lb, ub) # η
        (:mixed, f::MixedConstraint, lb, ub) # ψ
        (:variable, f::VariableConstraint, lb, ub) # θ
```

**Comment by jbcaillau** [comment]
@PierreMartinon any preliminary comments?

> @PierreMartinon aiming to providing inplace function as a result of `nlp_constraints!`, having inplace signatures for `ξ, η, ψ, ϕ, θ`:
> 
> ```julia
> julia> (ξl, ξ, ξu), (ηl, η, ηu), (ψl, ψ, ψu), (ϕl, ϕ, ϕu), (θl, θ, θu),
>     (ul, uind, uu), (xl, xind, xu), (vl, vind, vu) = nlp_constraints!(ocp)
> ```
> 
> Related to: [control-toolbox/CTDirect.jl#188](https://github.com/control-toolbox/CTDirect.jl/issues/188)

**Comment by jbcaillau** [comment]
@PierreMartinon back on this issue. on your side, ready for inplace in CTDirect.jl with trapezoidal scheme?

**Comment by jbcaillau** [comment]
> @ocots I'll need some help to update the unit tests.

@ocots we'll need to be able to run tests like

```julia
    @def o begin
        t ∈ [ 0, 1 ], time
        x = [ r, v ] ∈ R², state
        u ∈ R, control
        w = r + 2v
        r(0) == 0,    (1)
        v(0) == 1,    (♡)
        ẋ(t) == [ v(t), w(t)^2 ]
        ∫( u(t)^2 + x₁(t) ) → min
    end
    x = [ 1, 2 ]
    x0  = 2 * x
    xf  = 3 * x
    u = 3
    @test constraint(o, :eq1)(x0, xf) == x0[1]
    @test constraint(o, Symbol("♡"))(x0, xf) == x0[2]
    @test o.dynamics(x, u) == [ x[2], (x[1] + 2x[2])^2 ]
    @test o.lagrange(x, u) == u^2 + x[1]
```

It is better *not* to rewrite test but to update the getters (such as `constraint`) so that they take care of the functions now being in place. My question: can you please remind me what getters are available for dynamics and the three different costs? (Using getters in the test would be nicer, too.)

**Comment by ocots** [comment]
Getters:

https://github.com/control-toolbox/CTBase.jl/blob/5db9d88a096e8a515aa289dcbd30c72435679b5f/src/optimal_control_model-getters.jl#L565-L589

**Comment by jbcaillau** [comment]
@ocots excellent. do think you could `vscode` update [test_onepass.jl](https://github.com/control-toolbox/CTBase.jl/blob/main/test/test_onepass.jl) to replace field accesses by these getters? Then it should be fairly easy to reuse the existing tests with in place functions.

**Comment by jbcaillau** [comment]
> [Getters](https://control-toolbox.org/OptimalControl.jl/stable/api-ctbase/model.html#Getters):
> [...]

@ocots just for the record: no `bolza` getter, subsumed by `lagrange` + `mayer` ones, I suppose?

**Comment by PierreMartinon** [comment]
Hi guys, 
While you're at it, can you make it so that initial conditions are always before final conditions when building the boundary conditions ? 
Also, iirc mayer exists only in autonomous version ?

**Comment by jbcaillau** [comment]
@PierreMartinon 
> Hi guys, While you're at it, can you make it so that initial conditions are always before final conditions when building the boundary conditions ?

OK
> Also, iirc mayer exists only in autonomous version ?

Not sure that the question makes sense:
- either $t_0$ and $t_f$ are fixed and the mayer cost function is $g(x_0,x_f[,v])$ (where $v$ is another variable)
- or $t_f$, for instance, is free and then is (a component of) the variable, so $g(x_0, x_f, t_f)$ is expected

Same thing for (nonlinear) boundary conditions, BTW.

Am I missing sth?

**Comment by ocots** [comment]
Parametric type:

```julia
struct TypeParamExample{T<:Number}
    x::T
end
```

and for a function:

```julia
julia> function f(x::T, y::T) where {T <: Number}
       return x + y
       end
f (generic function with 1 method)

julia> f(1, 2)
3

julia> f(1, 2.0)
ERROR: MethodError: no method matching f(::Int64, ::Float64)

Closest candidates are:
  f(::T, ::T) where T<:Number
   @ Main REPL[5]:1

Stacktrace:
 [1] top-level scope
   @ REPL[7]:1
```

**Comment by joseph-gergaud** [comment]
@jbcaillau 
The scalar case for the constraints must be treated.

**Comment by ocots** [comment]
Voir : 

- https://docs.julialang.org/en/v1/manual/performance-tips/#man-performance-value-type
- https://docs.julialang.org/en/v1/manual/performance-tips/#kernel-functions

**Comment by jbcaillau** [comment]
> @jbcaillau The scalar case for the constraints must be treated.

@joseph-gergaud @PierreMartinon should be OK provided in place functions returned by `nlp_constraints!` are called with a (slice of) vector as first arg. may be an exception for Lagrange cost, to be checked. in any case, the possible generated error should be clear enough 🤞🏾

**Comment by jbcaillau** [comment]
- [ ] @jbcaillau adapt getters (`constraint`, `dynamics`, `lagrange`, `mayer`) to transform in place into out of place

**Comment by jbcaillau** [comment]
@PierreMartinon catch-up this Monday 9/9 at 14:00 on zoom
https://univ-cotedazur.zoom.us/my/caillau

@ocots @joseph-gergaud welcome if you're around!
