### ISSUE TITLE
Getters

### ISSUE THREAD

**Issue by ocots** [control-toolbox/CTBase.jl#244]
We have introduced some getters for `OptimalControlModel`. We should do the same for the solution `OptimalControlSolution`.

Then, we should restructure the code to have the getters in one separate file. This will simplify the API doc for the getters.

**Comment by PierreMartinon** [comment]
See also the question about new optional fields for discrete solutions https://github.com/control-toolbox/CTBase.jl/issues/144#issuecomment-2288393413
