### ISSUE TITLE
Formatter

### ISSUE THREAD

**Issue by ocots** [control-toolbox/CTBase.jl#253]
Try automatic Julia formatter: https://github.com/JuliaSmoothOptimizers/ADNLPModels.jl/blob/main/.github/workflows/Formatter.yml

But first, try manually.

**Comment by jbcaillau** [comment]
What does this do? Automatic reformats your code?

**Comment by ocots** [comment]
> What does this do? Automatic reformats your code?

Don't know yet.

**Comment by ocots** [comment]
Closed in favor of https://github.com/control-toolbox/CTBase.jl/issues/142.

**Comment by ocots** [comment]
> What does this do? Automatic reformats your code?

Yes and a PR then.
