### ISSUE TITLE
Update OptimalControlSolution: type, getters, setters

### ISSUE THREAD

**Issue by ocots** [control-toolbox/CTBase.jl#255]
> @PierreMartinon Do you need more than:
> 
> ```julia
> T = sol.times         # T = [t0, t1, ...]
> X = sol.state.(T)     # X = [x0, x1, ...]
> U = sol.control.(T)
> P = sol.costate.(T)
> ```
> 
> and
> 
> ```julia
> x = ctinterpolate(T, ...)
> p = ctinterpolate(T, ...)
> u = ctinterpolate(T, ...)
> ```

You lost me there :D 

What I meant is, we currently have the functions `state, control, costate`, and I'd like to have additional vector `state_d, control_d, costate_d`, to store discrete trajectories. This discrete part would be used when exporting to JSON text format, instead of the discrete solution struct I currently use. 

In the case of direct methods these vectors would store the original discrete solution, and in other cases it would simply default to apply the functions to a given time grid.

Ah, while we're on `OptimalControlSolution`, here is the list of keys for the different constraints and multipliers (other than costate), since these vectors and functions are currently saved in the `infos` dictionary of the solution. Maybe we could add explicit fields in the struct instead of dumping everything in the dictionary ? Note: I chose to return functions (ie interpolate) for everything related to path constraints, including 'boxes' on state and control variables, and keep vectors for boundary conditions and optimization variables constraints.

Vectors: `:boundary_constraints, :mult_boundary_constraints, :variable_constraints, :mult_variable_constraints, :mult_variable_box_lower, :mult_variable_box_upper`

Functions: `:control_constraints, :mult_control_constraints, :state_constraints, :mult_state_constraints, :mixed_constraints, :mult_mixed_constraints, :mult_state_box_lower, :mult_state_box_upper, :mult_control_box_lower, :mult_control_box_upper`

_Originally posted by @PierreMartinon in https://github.com/control-toolbox/CTBase.jl/issues/144#issuecomment-2301801915_

**Comment by ocots** [comment]
@PierreMartinon For what I understand, we have:

```julia
T = sol.times # or sol.time_grid now i think
state_d = sol.state.(T) 
control_d = sol.control.(T)
costate_d = sol.costate.(T)
```

or with the getters

```julia
T = time_grid(sol)
state_d = state(sol).(T) 
control_d = control(sol).(T)
costate_d = costate(sol).(T)
```

So I do not think it is a good idea to add fields for the discretized state, control and costate. It will be redundant and source of errors. However, we can add getters to get them:

```julia
state_d = state_discretized(sol)
control_d = control_discretized(sol)
costate_d = costate_discretized(sol)
```

**Comment by ocots** [comment]
In the `OptimalControlSolution`, I propose to add the fields:

Vectors: `:boundary_constraints, :mult_boundary_constraints, :variable_constraints, :mult_variable_constraints, :mult_variable_box_lower, :mult_variable_box_upper`

Functions: `:control_constraints, :mult_control_constraints, :state_constraints, :mult_state_constraints, :mixed_constraints, :mult_mixed_constraints, :mult_state_box_lower, :mult_state_box_upper, :mult_control_box_lower, :mult_control_box_upper`

with the associated getters.

Moreover, the constructor need to be updated.

I propose also to add setters for all the fields. The constructor must use the setters.

**Comment by PierreMartinon** [comment]
Hi, reopening this one for a quality-of-life point :D 

Currently the fields related to variables are not present if the OCP is not variable dependent. While this certainly makes sense, this gives two separate constructor calls and requires a test before choosing the correct one.

Could we just pass `nothing` values to everything variable-related in the variable-independent case ?

Or is there already a way to use the variable case constructor even for variable independent OCPs ?

**Comment by ocots** [comment]
You can uncomment:

https://github.com/control-toolbox/CTBase.jl/blob/1480852e69d6de96f56719b3b3026cadbfe6deef/src/optimal_control_solution-setters.jl#L103

and

https://github.com/control-toolbox/CTBase.jl/blob/1480852e69d6de96f56719b3b3026cadbfe6deef/src/optimal_control_solution-setters.jl#L113-L116
