### ISSUE TITLE
OrdinalRange vs UnitRange

### ISSUE THREAD

**Issue by BaptisteCbl** [control-toolbox/CTBase.jl#26]
https://github.com/control-toolbox/CTBase.jl/blob/d9b6cd6c27dd125c60f9e8e9f57eeb7eb9e9aa92/src/model.jl#L179

[OrdinalRange](https://docs.julialang.org/en/v1/base/collections/#Base.OrdinalRange) seems more adapted because it contains both StepRange and UnitRange

**Comment by ocots** [comment]
With `OrdinalRange` we can have things like `1:2:5`.

**Comment by jbcaillau** [comment]
@BaptisteCbl nice idea. Please fork this taking into account side effects, *e.g.* additional matches needed in `constraint-type`](xxxxx):
```julia
constraint_type(e, t, t0, tf, x, u) =
    @match [ has(e, x, t0), has(e, x, tf), has(e, u, t), has(e, x, t), has(e, u, t0), has(e, u, tf) ] begin
        [ true , false, false, false, false, false ] => @match e begin
            :( $y[$i:$j]($s) ) => (y == x && s == t0) ? (:initial, i:j     ) : :other
            :( $y[$i   ]($s) ) => (y == x && s == t0) ? (:initial, Index(i)) : :other
            _                  => (:boundary, replace_call(e, x, t0, Symbol(x, "#0"))) end
```

**Comment by jbcaillau** [comment]
@BaptisteCbl Hi, what about this issue?

**Comment by BaptisteCbl** [comment]
Hello, I made the changes in a new branch [unit-to-ordinal](https://github.com/control-toolbox/CTBase.jl/tree/unit-to-ordinal), I will make sure I did not forget any side effects and make a pull request in the next days.
