### ISSUE TITLE
[Dev] Avoid generic types in struct

### ISSUE THREAD

**Issue by ocots** [control-toolbox/CTBase.jl#287]
See https://github.com/control-toolbox/CTBase.jl/pull/271#discussion_r1745922118.

This

```julia
struct CallableType{U}
    f::Function
end
```

should be replaced by

```julia
struct CallableType{T<:Function, U}
    f::T
end
```

**Comment by amontoison** [comment]
Abstract vs concrete type:
https://gensoft.pasteur.fr/docs/julia/1.4.1/manual/performance-tips.html#Avoid-fields-with-abstract-type-1

**Comment by ocots** [comment]
```julia
julia> mutable struct MyType{T<:AbstractFloat}
           a::T
       end
```

is better choice than

```julia
julia> mutable struct MyStillAmbiguousType
           a::AbstractFloat
       end
```

**Comment by ocots** [comment]
The same best practices also work for container types:

```julia
julia> struct MySimpleContainer{A<:AbstractVector}
           a::A
       end

julia> struct MyAmbiguousContainer{T}
           a::AbstractVector{T}
       end
```

**Comment by amontoison** [comment]
@ocots 
```julia
help?> isconcretetype
search: isconcretetype

  isconcretetype(T)

  Determine whether type T is a concrete type, meaning it could have direct instances (values x
  such that typeof(x) === T).

  See also: isbits, isabstracttype, issingletontype.

  Examples
  ≡≡≡≡≡≡≡≡

  julia> isconcretetype(Complex)
  false
  
  julia> isconcretetype(Complex{Float32})
  true
  
  julia> isconcretetype(Vector{Complex})
  true
  
  julia> isconcretetype(Vector{Complex{Float32}})
  true
  
  julia> isconcretetype(Union{})
  false
  
  julia> isconcretetype(Union{Int,String})
  false
```
`Union{...}` is not a concrete type, which is why I recommended adding more parameters to your structure.

**Comment by ocots** [comment]
Thanks. But our model can be constructed incrementally and it may not be so costly since it is transcribed when we solve it. But the callable type are called many times so I think this is more crucial. I am updating these types.

**Comment by ocots** [comment]
Thanks. But our model can be constructed incrementally and it may not be so costly since it is transcribed when we solve it. But the callable type are called many times so I think this is more crucial. I am updating these types.

**Comment by ocots** [comment]
@ocots Replace 

https://github.com/control-toolbox/CTBase.jl/blob/3275d6be050c2fb0a927662f9845309ad28e93ce/src/functions.jl#L38

by 

```julia
function BoundaryConstraint(f::Function, VD::VariableDependence)
```
