### ISSUE TITLE
[Bug] Breakage is broken

### ISSUE THREAD

**Issue by ocots** [control-toolbox/CTBase.jl#296]
Breakage is broken

```bash
Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v2`. 
Learn more: https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/
```

See [this job](https://github.com/control-toolbox/CTBase.jl/actions/runs/10818052313/job/30012817296?pr=294) for instance.

**Comment by ocots** [comment]
@amontoison Do you have this problem too? :-(

**Comment by amontoison** [comment]
@ocots 
I didn't encounter this bug yet but your should use the version `v4` of `actions/upload-artifact`.

**Comment by ocots** [comment]
@amontoison Yes but now we have a new [bug](https://github.com/control-toolbox/CTBase.jl/actions/runs/10855783400/job/30129090213?pr=294#step:7:15) with the v4:

```bash
With the provided path, there will be 2 files uploaded
Artifact name is valid!
Root directory input is valid!
Error: Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run
```

**Comment by amontoison** [comment]
Can you send me the link to the .yml file?
I can maybe have before the conference AD2024.

**Comment by ocots** [comment]
It's this [Breakage.yml](https://github.com/control-toolbox/CTBase.jl/blob/main/.github/workflows/Breakage.yml) (here it is with the v2) file. I think that the `.yml` which makes the comment will need to be updated. It's this [CommentPR.yml](https://github.com/control-toolbox/CTBase.jl/blob/main/.github/workflows/CommentPR.yml).

@amontoison Thanks!
