### ISSUE TITLE
Forget to make a PR

### ISSUE THREAD

**Issue by ocots** [control-toolbox/CTBase.jl#31]
I have done some modifications. I wanted to make a PR but I have pushed into `main` directly. Oups.

## Bolza

source 

https://github.com/control-toolbox/CTBase.jl/blob/7e52c84aa2665772009c97f9d8fb0d688cac7208/src/model.jl#L556

and test

https://github.com/control-toolbox/CTBase.jl/blob/7e52c84aa2665772009c97f9d8fb0d688cac7208/test/test_model.jl#L46

## Remove getters for an optimal control model

I have removed them since it was not consistent. Some fields had getters and others didn't.

## Documentation

- almost every function, type and const has a docstring.
- I have created a page for the doc of every source file, see https://github.com/control-toolbox/CTBase.jl/tree/main/docs/src

I only put the doc of the public functions in the corresponding doc page:

https://github.com/control-toolbox/CTBase.jl/blob/7e52c84aa2665772009c97f9d8fb0d688cac7208/docs/src/api-callbacks.md?plain=1#L1

And I have created a page with the doc of all private functions: https://github.com/control-toolbox/CTBase.jl/blob/main/docs/src/api-developers.md

**Comment by ocots** [comment]
@jbcaillau @PierreMartinon @joseph-gergaud I invite you to take a look to the changes. I will make a release later.

**Comment by ocots** [comment]
You can see the actual documentation here: https://control-toolbox.github.io/CTBase.jl/dev/

**Comment by ocots** [comment]
Feel free to update / complete the doc!

**Comment by jbcaillau** [comment]
_You too like to live dangerously..._

**Comment by ocots** [comment]
But I always test and make the doc locally :-)
