### ISSUE TITLE
Improve covering

### ISSUE THREAD

**Issue by ocots** [control-toolbox/CTBase.jl#34]
I have added some unit tests.

Still need to improve covering of:

- [x] @j-l-s [ctparser.jl](https://app.codecov.io/gh/control-toolbox/CTBase.jl/blob/main/src/ctparser.jl)
- [x] @jbcaillau [model.jl](https://app.codecov.io/gh/control-toolbox/CTBase.jl/blob/main/src/model.jl)
- [x] @ocots [utils.jl](https://app.codecov.io/gh/control-toolbox/CTBase.jl/blob/main/src/utils.jl)

**Comment by jbcaillau** [comment]
@ocots We (I...) probably have downgraded the coverage with new stuff in parsing / variables. To be continued, anyway.

**Comment by ocots** [comment]
Yep.
