### ISSUE TITLE
Box constraints for the direct method & more

### ISSUE THREAD

**Issue by ocots** [control-toolbox/CTBase.jl#4]
The constraints have to be added in the `CTBase` package. Then, it will be possible to update the `CTDirect` package.

**Remarks.**

* The `ipopt` solver is more efficient if the box constraints are taken into account. 
* See also [Issue 63](https://github.com/control-toolbox/OptimalControl.jl/issues/63).

**Comment by PierreMartinon** [comment]
I'll start integrating the box constraints in the direct part next week !

**Comment by joseph-gergaud** [comment]
Je voulais aussi m'y remettre la semaine prochaine. On pourrait travaille  ensemble comme à Nice (voir mes dispo en pièce jointe).

[Calendrier — semaine — de 12:03:2023 à 18:03:2023.pdf](https://github.com/control-toolbox/CTBase.jl/files/10940445/Calendrier.semaine.de.12.03.2023.a.18.03.2023.pdf)

**Comment by PierreMartinon** [comment]
Oui ! Je suis libre sauf vendredi, donc je pourrais passer mercredi ? 
(lundi et mardi ont l'air un peu pris)
Pierre

**Comment by joseph-gergaud** [comment]
Pierre,

On dit mercredi à 9h00 dans  mon bureau ?

Joseph

**Comment by jbcaillau** [comment]
@ocots Looks like these functions are only used in the test: correct? With the additional type of constraints, these computations must be updated.

```julia
function initial_condition(ocp::OptimalControlModel)
function final_condition(ocp::OptimalControlModel)
function initial_constraint(ocp::OptimalControlModel)
function final_constraint(ocp::OptimalControlModel)
```

**Comment by jbcaillau** [comment]
@ocots At least used in `CTDirectShooting.jl`

**Comment by ocots** [comment]
The functions`final_constraint` and `initial_condition` are used in [CTDirectShooting/src/utils.jl](https://github.com/control-toolbox/CTDirectShooting.jl/blob/f6f56fb2bba451bd630ff9bf1733d01458835dcb/src/utils.jl#L4)  in the following function.
```julia
function parse_ocp_direct_shooting(ocp::OptimalControlModel)
    # parsing ocp
    dy = dynamics(ocp)
    co = lagrange(ocp)
    cf = final_constraint(ocp)
    x0 = initial_condition(ocp)
    n = state_dimension(ocp)
    m = control_dimension(ocp)
    return dy, co, cf, x0, n, m
end
```

This function `parse_ocp_direct_shooting` is used to define the [direct shooting problem](https://github.com/control-toolbox/CTDirectShooting.jl/blob/f6f56fb2bba451bd630ff9bf1733d01458835dcb/src/problem.jl#L10) which is given to the unconstrained optimization solver `CTOptimization.jl` and is also used to build the [solution](https://github.com/control-toolbox/CTDirectShooting.jl/blob/f6f56fb2bba451bd630ff9bf1733d01458835dcb/src/solution.jl#L26).

**Remark.** The functions`final_constraint` and `initial_condition` are not used to check the validity of the optimal control problem like I have said. It is true than with the direct shooting method we cannot solve problems with constraints for the moment, but the [checking](https://github.com/control-toolbox/CTDirectShooting.jl/blob/main/src/solve.jl#L45) is done simply by:
```julia
    # check validity
    ξ, ψ, ϕ = nlp_constraints(ocp)
    dim_ξ = length(ξ[1])      # dimension of the boundary constraints
    dim_ψ = length(ψ[1])
    if dim_ξ != 0 && dim_ψ != 0
        error("direct shooting is implemented for problems without constraints")
    end
```

**Comment by jbcaillau** [comment]
@ocots OK I if simply move the two functions `initial_condition` and `final_constraint` (that assume the simple form you used for the problem) into `CTDirectShooting/src/utils.jl`? Will it suffice?

**Comment by ocots** [comment]
We can write the functions here to keep it in mind and you can remove them from `CTBase.jl`.

```julia
function initial_condition(ocp::OptimalControlModel) 
    cs = constraints(ocp)
    x0 = nothing
    for (_, c) ∈ cs
        type, _, _, val = c
        if type == :initial
             x0 = val
        end
    end
    return x0
end
function final_condition(ocp::OptimalControlModel) 
    cs = constraints(ocp)
    xf = nothing
    for (_, c) ∈ cs
        type, _, _, val = c
        if type == :final
             xf = val
        end
    end
    return xf
end
function initial_constraint(ocp::OptimalControlModel) 
    cs = constraints(ocp)
    c0 = nothing
    for (_, c) ∈ cs
        type, _, f, val = c
        if type == :initial
            c0 = x -> f(x) - val
        end
    end
    return c0
end
function final_constraint(ocp::OptimalControlModel) 
    cs = constraints(ocp)
    cf = nothing
    for (_, c) ∈ cs
        type, _, f, val = c
        if type == :final
            cf = x -> f(x) - val
        end
    end
    return cf
end
```

**Comment by PierreMartinon** [comment]
NB. With Joseph we started a branch in CTDirect that is compatible with the new nlp_constraints function including the pure state constraints and boxes

**Comment by ocots** [comment]
@jbcaillau Not sure that this should be a `Vector{Int}` since you append some range: https://github.com/control-toolbox/CTBase.jl/blob/constraints/src/model.jl#L229

**Comment by ocots** [comment]
Scalar bounds or vectorial: 
- https://github.com/control-toolbox/CTBase.jl/blob/constraints/src/model.jl#L145
- https://github.com/control-toolbox/CTBase.jl/blob/constraints/src/model.jl#L158

**Comment by jbcaillau** [comment]
OK: we can 
- [ ] @jbcaillau add both in abstract and functional form the case of a single constant for a whole range (= same value for all indices, *e.g.* zero)

**Comment by ocots** [comment]
For me it was ok to give a vector of the same size as the range. Still, the most important for @PierreMartinon and @joseph-gergaud is just in which format we give them the constraints, via `nlp_constraints` function.

**Remark.** the name `nlp_constraints` is pas terrible terrible :-)

**Comment by PierreMartinon** [comment]
Flat non-ordered is ok for us.

> **Remark.** the name `nlp_constraints` is pas terrible terrible :-)
ocp_constraints ?

**Comment by jbcaillau** [comment]
@PierreMartinon @joseph-gergaud For the record:
- infos on the format in this [previous post](https://github.com/control-toolbox/CTBase.jl/issues/4#issuecomment-1462862098)
- tests: doing 🤞🏾

**Comment by jbcaillau** [comment]
@ocots tests passed in branch `constraints`:
- PR to come 🤞🏾
- I have suppressed `initial_condition`, *etc.* (see [here](https://github.com/control-toolbox/CTBase.jl/issues/4#issuecomment-1468733175)) but not yet moved them into `CTDirectShooting` 
- some comments are in order regarding the scalar / vectorial thing for state and control (to be discussed)

**Comment by ocots** [comment]
I will handle `CTDirectShooting`. No problemo.
I have made the review but I prefer not to change the code myself.

**Comment by jbcaillau** [comment]
@ocots Cannot see the review!
> I have made the review but I prefer not to change the code myself.

**Comment by ocots** [comment]
You should see comments directly in the PR: https://github.com/control-toolbox/CTBase.jl/pull/10

**Comment by jbcaillau** [comment]
@ocots please merge [this PR](https://github.com/control-toolbox/CTBase.jl/pull/15/files) after checking comments in review

**Comment by jbcaillau** [comment]
@ocots @joseph-gergaud @PierreMartinon OK for a meeting next Thursday (30/3)?

/polls Option1 'Option 2' "Option 3"

**Comment by ocots** [comment]
Any time.

**Comment by jbcaillau** [comment]
> Any time.

good. installed this [poll app](https://github.com/apps/polls), does not seem to work 💩

**Comment by jbcaillau** [comment]
@ocots have you eventually moved [this](https://github.com/control-toolbox/CTBase.jl/issues/4#issuecomment-1468733175) somewhere in `CTDirect.jl`?

**Comment by ocots** [comment]
I didn't move it but you have something similar here:

- https://github.com/control-toolbox/CTDirectShooting.jl/blob/main/src/utils.jl#L18
- https://github.com/control-toolbox/CTProblems.jl/blob/main/test/utils.jl

I will replace these pieces of code (piece of codes / piece of code) when I will have something good.

**Comment by ocots** [comment]
Test:

/polls Option1 'Option 2' "Option 3"

**Comment by ocots** [comment]
Maybe poll is only in the description of a new issue.

**Comment by jbcaillau** [comment]
@PierreMartinon @joseph-gergaud https://github.com/control-toolbox/CTBase.jl/issues/4#issuecomment-1483923387

**Comment by corentinmartinon** [comment]
> @ocots @joseph-gergaud @PierreMartinon OK for a meeting next Thursday (30/3)?
> 
> /polls "10:00" "15:00" "17:00"

Pas de contrainte pour moi

**Comment by PierreMartinon** [comment]
Pas de contrainte pour moi

**Comment by jbcaillau** [comment]
> > @ocots @joseph-gergaud @PierreMartinon OK for a meeting next Thursday (30/3)?
> > /polls "10:00" "15:00" "17:00"
> 
> Pas de contrainte pour moi

c'est qui Corentin Martinon ?

**Comment by jbcaillau** [comment]
> > @ocots @joseph-gergaud @PierreMartinon OK for a meeting next Thursday (30/3)?
> > /polls "10:00" "15:00" "17:00"
> 
> Pas de contrainte pour moi

c'est qui Corentin Martinon ?

**Comment by jbcaillau** [comment]
> > @ocots @joseph-gergaud @PierreMartinon OK for a meeting next Thursday (30/3)?
> > /polls "10:00" "15:00" "17:00"
> 
> Pas de contrainte pour moi

c'est qui Corentin Martinon ?

**Comment by jbcaillau** [comment]
> > @ocots @joseph-gergaud @PierreMartinon OK for a meeting next Thursday (30/3)?
> > /polls "10:00" "15:00" "17:00"
> 
> Pas de contrainte pour moi

c'est qui Corentin Martinon ?

**Comment by ocots** [comment]
je commente

**Comment by corentinmartinon** [comment]
C'est mon altesse :D

**Comment by jbcaillau** [comment]
✅

> Nous ne sommes pas schizophrenes
> (au passage c'est pas un peu bizarre que mon autre compte puisse repondre ici ?)

public repo. makes sense

**Comment by joseph-gergaud** [comment]
C'est ok pour moi jeudi à 10h00

**Comment by jbcaillau** [comment]
@ocots @PierreMartinon @joseph-gergaud 10:00 it is, this Thursday
[webex](https://inria.webex.com/meet/jean-baptiste.caillau)
