### ISSUE TITLE
Functional (and abstract): allow to label dynamics

### ISSUE THREAD

**Issue by jbcaillau** [control-toolbox/CTBase.jl#41]
Change `model.jl` so that
- `:dynamic` constraint can be labelled
- when called with `constraint` returns the dynamics function

**Comment by ocots** [comment]
@BaptisteCbl Maybe you can take this issue. 

Is it clear?

**Comment by BaptisteCbl** [comment]
I will try to do so, it seems clear enough to me.

**Comment by ocots** [comment]
@jbcaillau is it still useful?

**Comment by jbcaillau** [comment]
I don't think so. Actually I propose to treat the dynamics alone, check #67. Closing this issue.
