### ISSUE TITLE
Subscripts

### ISSUE THREAD

**Issue by ocots** [control-toolbox/CTBase.jl#57]
https://github.com/control-toolbox/CTBase.jl/blob/c9f1039fe1df0c852602c9e81e65dd797e3e55a2/test/test_onepass.jl#L764

I don't know how you make automatically the aliases but you can use the function here: https://github.com/control-toolbox/CTBase.jl/blob/variable_constraints/src/utils.jl#L18

```julia
ctindices(12)
```

returns `12` as a subscripts. To create default values for the state, I do:

```
__state_names(n::Dimension) = n==1 ? "x" : [ "x" * ctindices(i) for i ∈ range(1, n)]
```

You can replace the test by:

```julia
@test ocp.state_names ==  [ "u" * ctindices(i) for i ∈ range(1, 9) ]
```

**Comment by jbcaillau** [comment]
✅ done
