### ISSUE TITLE
REPL maker

### ISSUE THREAD

**Issue by jbcaillau** [control-toolbox/CTBase.jl#64]
A nice idea of @j-l-s : [ReplMaker](https://github.com/MasonProtter/ReplMaker.jl) to parse an ocp from the REPL

**Comment by ocots** [comment]
That's very nice!

**Comment by jbcaillau** [comment]
@ocots REPL command wish list
```julia
/name
/show
/debug
/solve
/plot
/help
```

**Comment by ocots** [comment]
lol you just changed the commands

**Comment by ocots** [comment]
```julia

ct> DEBUG

parsing string: DEBUG

expression parsed: DEBUG

command: DEBUG

 debug mode off

ct> SHOW

 display model: on
 display code:  on
```

**Comment by ocots** [comment]
Yes it is not possible with `/` or `!`.

**Comment by jbcaillau** [comment]
must use a unary operator. test with `@dump` to check whether it parses in Julia or not. also important to distinguish from typical math writing as it is what guided the syntax of the DSL.

**Comment by ocots** [comment]
https://github.com/control-toolbox/CTBase.jl/assets/66357348/4a43ad8f-1cfd-4ac0-8781-dcecfedb4a9f

**Comment by jbcaillau** [comment]
OK with that. Then the rule is no tag iff full and simultaneous declaration of time, state, control (in this order), plus variable if needed. 

Note that we still need to parse and allow variable time bounds.

**Comment by ocots** [comment]
Just for save:

```julia
        @match e begin
            :( $e_, time                 ) => __add!(ct_repl, :time, e, history)
            :( $t ∈ [$a, $b]             ) => __add!(ct_repl, :time, :($t ∈ [$a, $b], time), history)
            :( $e_, state                ) => __add!(ct_repl, :state, e, history)
            :( $e_, control              ) => __add!(ct_repl, :control, e, history)
            :( $x, $u ∈ $X, $U ) || :( ($x, $u) ∈ $X × $U ) || :( ($x, $u) ∈ $X * $U )=> begin
                __add!(ct_repl, :state, :($x ∈ $X, state), history)
                __add!(ct_repl, :control, :($u ∈ $U, control), history)
            end
            :( $e_, variable             ) => __add!(ct_repl, :variable, e, history)
            :( $x, $u, $v ∈ $X, $U, $V ) || :( ($x, $u, $v) ∈ $X × $U × $V ) || :( ($x, $u, $v) ∈ $X * $U * $V )=> begin
                __add!(ct_repl, :state, :($x ∈ $X, state), history)
                __add!(ct_repl, :control, :($u ∈ $U, control), history)
                __add!(ct_repl, :variable, :($v ∈ $V, variable), history)
            end
            :( $a = $e1                  ) => __add!(ct_repl, :alias, e, history)
            :( ∂($x)($t) == $e1          ) => __add!(ct_repl, :dynamics, e, history)
            :( ∂($x)($t) == $e1, $label  ) => __add!(ct_repl, :dynamics, e, history)
            :( $e1 == $e2                ) => __add!(ct_repl, :constraints, e, history)
            :( $e1 == $e2, $label        ) => __add!(ct_repl, :constraints, e, history)
            :( $e1 ≤  $e2 ≤  $e3         ) => __add!(ct_repl, :constraints, e, history)
            :( $e1 ≤  $e2 ≤  $e3, $label ) => __add!(ct_repl, :constraints, e, history)
            :( $e_ → min                 ) => __add!(ct_repl, :objective, e, history)
            :( $e_ → max                 ) => __add!(ct_repl, :objective, e, history)
            _ => (println("\nct parsing error\n\nType HELP to see the list of commands or enter a valid expression to update the model."); return nothing)
        end
```

**Comment by jbcaillau** [comment]
@ocots need to add somewhere the way to start the REPL (`__init_repl()`...) manually. I assume that `using CTBase` supposedly does the job but not working on my side.

**Comment by ocots** [comment]
To launch `__init_repl`, `Base.active_repl` must be defined but it is only when the REPL is running. I don't manage to launch the method when making the `using`. 

I tried, see:

https://github.com/control-toolbox/CTBase.jl/blob/88d0550760172991cd68e687f028730a41f19472/src/CTBase.jl#LL153C1-L153C47

Maybe, with a wait condition we could run the init later.

**Comment by ocots** [comment]
I note to print the ocp only if it is incomplete, that is when we have the table.

**Comment by jbcaillau** [comment]
@ocots some minor things to fix:
- declaring `tf, variable` then `t ∈ [ 0, tf ]` doesn't seem to work (the `variable` declaration is misplaced - before the `time` one)
- when there is an error, the line nevertheless seems to be stored (requires to `UNDO`)
- since aliases are not expanded when you pre-parse the code, expressions like `ẋ(t)` are not recognised for dynamics (only `xxxxx` syntax is), leading to side effects as below (multiple dynamics)

All in all, I advocate a very simple pre-parsing, not duplicating the grammar:
- either no pre-parsing at all, relying on one-only declaration (but possibility to `UNDO`)
- or (seems more user friendly), possibility of redeclaration of `time, state, control, variable, dynamics, objective` (`constraints` all remain, being *cumulative*) according to sth like
```julia
        @match e begin
            :( $e_, time        ) => __add!(ct_repl, :time, e, history)
            :( $e_, state       ) => __add!(ct_repl, :state, e, history)
            :( $e_, control     ) => __add!(ct_repl, :control, e, history)
            :( $e_, variable    ) => __add!(ct_repl, :variable, e, history)
            :( ∂($x)($t) == $e_ ) => __add!(ct_repl, :dynamics, e, history)
            :( $e_ → min        ) => __add!(ct_repl, :objective, e, history)
            :( $e_ → max        ) => __add!(ct_repl, :objective, e, history)
            _                     => __add!(ct_repl, :constraints, e, history)
        end
```
![IMG_2104](https://github.com/control-toolbox/CTBase.jl/assets/62183989/77d41147-5f91-40e6-aa99-f52e16cd51f1)

**Comment by ocots** [comment]
Ok thanks.

But you do not use the last version.

**Comment by jbcaillau** [comment]
@ocots thanks for the update on `ct-REPL`. probably need to `try ... catch` everything (= the main loop) to avoid hard backtraces (@j-l-s can't stand them 🥲), *e.g.* when trying sth like `NAME`, `SHOW=0`, *etc.*

**Comment by ocots** [comment]
Yes indeed. This is version 0. Feel free to update as you wish.
