### ISSUE TITLE
Functional: revise

### ISSUE THREAD

**Issue by jbcaillau** [control-toolbox/CTBase.jl#67]
@ocots @PierreMartinon @joseph-gergaud Proposals of updates for the functional definition of an ocp:
- `constraint!` addiwith `kwargs` when `type ∈ [ :initial, :final, :boundary, :control, :state, :mixed, :variable ]` 
```julia
constraint!(ocp, type; range=..., fun=..., val=..., lb=..., ub=..., label=...)
```
More readable (?) than and compatible with current syntax (preserved).
- instead of adding the (trivial) possibility to label dynamics / dynamical constraint, may be better to treat them with a specific command (small API change, then):
```julia
dynamics!(ocp, fun; in_place=false) # or dynamics!{:out_place}(...)
```
Actually, `time!`, `state!`, `control!`, `variable!`, `dynamics!`, `cost!` are more or less one-shot declarations, *vs.* `constraints!` that is additive.

**Comment by ocots** [comment]
I think it is clearer to have keywords.

But for the moment, for instance, it is not possible to call `constraint!` on a range if the type is `mixed`. So we would have to check and give an appropriate response to the user. 

I guess also that it won't be possible to set both `range` and `fun`?

I am ok for `dynamics`.

**Comment by jbcaillau** [comment]
We can do whatever we think is good! In the case of mixed constraints, I think it doesn't make sense to have a range (a range on what, state or control? knowing that ranges - that is box constraints - are possible both for state and control, separately).

**Comment by jbcaillau** [comment]
@ocots @BaptisteCbl Todo:
- [ ] for time, state, control and variable, only one declaration 
- [ ] *idem* for dynamics and objective (prevent multiple declaration, not just a warning)
- but constraints are cumulative (`constraint!` can - of course - be called several times)

**Comment by ocots** [comment]
Yes we have to make minimal tests since later we will accept for instance to declare with one expression the dimension of the state and some box constraints.

So when we need a dimension just test before.

**Comment by jbcaillau** [comment]
@BaptisteCbl there are some references to the old way to define the dynamics (through `constraint!(..., :dynamics, ...)` in some other repos of the organisation, *e.g.* [here](https://control-toolbox.org/OptimalControl.jl/stable) Can you please have a look?

**Comment by ocots** [comment]
I don't understand why you say this. This should be updated when we will use the new release. The doc depends on the current release of the package.

**Comment by jbcaillau** [comment]
OK. The way to maintain the coherence between the releases of several repos is not clear to me.

**Comment by ocots** [comment]
Note that on the doc you can choose the version at bottom left of the page.
