### ISSUE TITLE
Code cleaning

### ISSUE THREAD

**Issue by jbcaillau** [control-toolbox/CTBase.jl#74]
@ocots @BaptisteCbl Would be nice to use `@match` for this kind of sequence (there are quite a few in the code 🥲)
![IMG_2103](https://github.com/control-toolbox/CTBase.jl/assets/62183989/b42afd21-d8d3-4623-9d86-71e30dd89adc)

**Comment by jbcaillau** [comment]
Write instead sth like (matching on type of value, not value of types)
```julia
@match ocp begin
    ::OptimalControlModel{Autonomous, Fixed} => ...
    ::OptimalControlModel{Autonomous, NonFixed} => ...
    ::OptimalControlModel{NonAutonomous, Fixed} => ...
    _ => ...
end
```

**Comment by ocots** [comment]
Done!

**Comment by jbcaillau** [comment]
@BaptisteCbl @ocots thank you guys! Progress 👍🏽
