### ISSUE TITLE
ct-REPL: unknown command

### ISSUE THREAD

**Issue by jbcaillau** [control-toolbox/CTBase.jl#78]
@ocots unknown REPL command throws an error
![IMG_2117](https://github.com/control-toolbox/CTBase.jl/assets/62183989/58152538-9ca0-4f44-b24b-00f9e6b3e582)

**Comment by ocots** [comment]
What do you think we should do? I have types the function `add!` and it takes an `Expr`. Either I remove the type and si I try to parse everything or when it is not an expression I skip and return an error.

 Don't hesitate to modify the code.

**Comment by jbcaillau** [comment]
@ocots OK. I didn't it was that minimal 😅. We need to stay in the REPL loop, stating the proper error when it occurs. Looking at it and PR-ing to you.

**Comment by ocots** [comment]
There is a lot of code that can be removed since we do not parse anything anymore.

**Comment by ocots** [comment]
Maybe I make a pass before to clean a bit.

**Comment by ocots** [comment]
Done!

**Comment by jbcaillau** [comment]
@ocots back from Italy. having a look at it.
