### ISSUE TITLE
Release 0.7.0

### ISSUE THREAD

**Issue by joseph-gergaud** [control-toolbox/CTBase.jl#82]
1. In OptimalControlSolution  type, there is not the value of the variable v ;

2. The plot of the solution of the problem

```julia
n=1
m=1
t0=0
tf=1
x0=[0]
xf=[0]
ocp = Model()
state!(ocp, n)
control!(ocp, m)
time!(ocp, [t0, tf])
constraint!(ocp, :initial, x0, :initial_constraint)
#constraint!(ocp, :final, xf, :final_constraint)
constraint!(ocp, :control, -1, 1, :control_constraint)
dynamics!(ocp, (x, u) ->  -x[1] + u[1])
#objective!(ocp, :lagrange, (x, u) -> u[1]*u[1])
objective!(ocp, :mayer, (x0,xf) -> xf)
sol = solve(ocp, grid_size=20, print_level=5)
p1 = plot(sol)
```

the plot of the control and  of the costate is not  good (value of -1)

3. It will be better that CTBase as before five function with only vectors as argument. When we'll code the direct shooting method, we'll have to treat the  different case scalar, or vector as for  de Direct method ...

**Comment by ocots** [comment]
1. Ok. I will make the update.
2. Have you take a look to `sol.control` and `sol.costate`?
3.

**Comment by ocots** [comment]
I have added the field `variable`: https://github.com/control-toolbox/CTBase.jl/releases/tag/v0.7.1

**Comment by jbcaillau** [comment]
@joseph-gergaud I don't get what you mean point 3, but apparently @ocots does! Anyway, call me (phone) this Tuesday if you want to discuss this.

**Comment by jbcaillau** [comment]
@ocots issue resolved?

**Comment by ocots** [comment]
Not yet, but no answer from @joseph-gergaud

**Comment by ocots** [comment]
Problem solved by https://github.com/control-toolbox/CTBase.jl/pull/149
