### ISSUE TITLE
REPL: do not store / undo wrong command

### ISSUE THREAD

**Issue by jbcaillau** [control-toolbox/CTBase.jl#97]
@ocots when an expression is not correct, it should not be stored. For instance:
![IMG_2164](https://github.com/control-toolbox/CTBase.jl/assets/62183989/df4f1a5b-b8d7-4024-bcd1-d45ab7fad360)

**Comment by jbcaillau** [comment]
PS. And there is a bug on `UNDO`. It has just removed / undone a whole set of commands instead of the last one 🥲...

**Comment by ocots** [comment]
That's weird! I do not master this.

**Comment by ocots** [comment]
If you want, I can explain the code and then you can change everything! It will be simpler. I have to update `CTFlows`, `CTProblems`, make a release of `OptimalControl`...

**Comment by ocots** [comment]
Ok it was a small mistake :-(

**Comment by ocots** [comment]
See the PR.

**Comment by ocots** [comment]
Should be ok on the v0.7.3

**Comment by jbcaillau** [comment]
Thanks, looks fine on this test! Merging
